Repository LLNL/serac, pull requests merged in 2020-08, with the labels that each got.

#120 Guard CMake strings that could be empty
  cmake/thirdparty/FindMFEM.cmake
Labels: CS

#115 Add SLIC_*_IF_ROOT convenience macros
  src/common/logger.hpp
  src/docs/sphinx/logging.rst
  src/solvers/thermal_structural_solver.cpp
Labels: CS, enhancement, ready for review

#117 Add new Azure job for checking style
  azure-pipelines.yml
  scripts/azure-pipelines/linux-check.sh
  scripts/docker/dockerfile.in
  scripts/docker/dockerfile_clang-10
Labels: CS

#108 Switch to C++17 and use std::variant for managing MFEM coefficients
  .gitlab/ci/build_quartz.yml
  CMakeLists.txt
  azure-pipelines.yml
  host-configs/docker/docker-linux-ubuntu16.04-x86_64-clang@6.0.0.cmake
  scripts/docker/dockerfile_clang-6
  src/common/serac_types.hpp
  src/solvers/base_solver.cpp
  src/solvers/base_solver.hpp
  src/solvers/elasticity_solver.cpp
  src/solvers/nonlinear_solid_operators.cpp
  src/solvers/nonlinear_solid_operators.hpp
  src/solvers/nonlinear_solid_solver.cpp
  src/solvers/nonlinear_solid_solver.hpp
  src/solvers/thermal_operators.cpp
  src/solvers/thermal_operators.hpp
  src/solvers/thermal_solver.cpp
  src/solvers/thermal_solver.hpp
  tests/serac_component_bc.cpp
Labels: CS

#116 Adds the doxygen html to the readthedocs space
  .readthedocs.yml
  src/docs/CMakeLists.txt
  src/docs/conf.py
  src/docs/doxygen/CMakeLists.txt
  src/docs/doxygen/Doxyfile.in
  src/docs/index.rst
  src/docs/sphinx/CMakeLists.txt
Labels: documentation, enhancement, ready for review

#123 Deleting some leftover unused shared_ptrs
  src/solvers/nonlinear_solid_solver.cpp
Labels: CS, bug, ready for review

#129 Cleanup the doxygen documentation
  .clang-format
  src/coefficients/loading_functions.hpp
  src/coefficients/stdfunction_coefficient.hpp
  src/coefficients/traction_coefficient.hpp
  src/common/logger.hpp
  src/common/mesh_utils.hpp
  src/common/serac_types.hpp
  src/docs/doxygen/Doxyfile.in
  src/docs/sphinx/style_guide.rst
  src/drivers/serac.cpp
  src/integrators/hyperelastic_traction_integrator.hpp
  src/integrators/inc_hyperelastic_integrator.hpp
  src/integrators/wrapper_integrator.hpp
  src/solvers/base_solver.hpp
  src/solvers/elasticity_solver.hpp
  src/solvers/nonlinear_solid_operators.hpp
  src/solvers/nonlinear_solid_solver.hpp
  src/solvers/thermal_operators.hpp
  src/solvers/thermal_solver.hpp
  src/solvers/thermal_structural_solver.hpp
  tests/copy_elision.cpp
  tests/serac_stdfunction_coefficient.cpp
  tests/serac_wrapper_tests.cpp
Labels: documentation, ready for review

#130 Rearranging the public/protected/private chunks of classes
  src/coefficients/traction_coefficient.hpp
  src/integrators/hyperelastic_traction_integrator.hpp
  src/integrators/inc_hyperelastic_integrator.hpp
  src/solvers/base_solver.hpp
  src/solvers/elasticity_solver.hpp
  src/solvers/nonlinear_solid_operators.hpp
  src/solvers/nonlinear_solid_solver.hpp
  src/solvers/thermal_operators.hpp
  src/solvers/thermal_solver.hpp
  src/solvers/thermal_structural_solver.hpp
Labels: documentation, ready for review

#125 Add a signal handler
  src/common/CMakeLists.txt
  src/common/common.hpp
  src/common/logger.cpp
  src/common/logger.hpp
  src/common/mesh_utils.cpp
  src/common/terminator.cpp
  src/common/terminator.hpp
  src/drivers/serac.cpp
  src/solvers/base_solver.cpp
  src/solvers/elasticity_solver.cpp
Labels: CS

#128 Switch BoundaryCondition from struct to class to reflect invariants
  src/common/CMakeLists.txt
  src/common/boundary_condition.cpp
  src/common/boundary_condition.hpp
  src/common/common.hpp
  src/common/serac_types.hpp
  src/solvers/base_solver.cpp
  src/solvers/base_solver.hpp
  src/solvers/elasticity_solver.cpp
  src/solvers/nonlinear_solid_operators.cpp
  src/solvers/nonlinear_solid_operators.hpp
  src/solvers/nonlinear_solid_solver.cpp
  src/solvers/thermal_operators.cpp
  src/solvers/thermal_operators.hpp
  src/solvers/thermal_solver.cpp
Labels: CS, ready for review

#131 Wrap system solver into class
  src/solvers/CMakeLists.txt
  src/solvers/algebraic_solver.cpp
  src/solvers/algebraic_solver.hpp
  src/solvers/base_solver.hpp
  src/solvers/elasticity_solver.cpp
  src/solvers/nonlinear_solid_operators.cpp
  src/solvers/nonlinear_solid_operators.hpp
  src/solvers/nonlinear_solid_solver.cpp
  src/solvers/thermal_operators.cpp
  src/solvers/thermal_operators.hpp
  src/solvers/thermal_solver.cpp
  src/solvers/thermal_solver.hpp
  tests/serac_thermal_solver.cpp
Labels: CS, ready for review

#140 Fixing the docs for the WSL
  src/docs/index.rst
Labels: documentation, ready for review

#132 Second memory audit
  src/coefficients/stdfunction_coefficient.cpp
  src/coefficients/traction_coefficient.hpp
  src/docs/sphinx/style_guide.rst
  src/solvers/CMakeLists.txt
  src/solvers/base_solver.hpp
  src/solvers/elasticity_solver.cpp
  src/solvers/equation_solver.cpp
  src/solvers/equation_solver.hpp
  src/solvers/nonlinear_solid_operators.cpp
  src/solvers/nonlinear_solid_operators.hpp
  src/solvers/nonlinear_solid_solver.cpp
  src/solvers/nonlinear_solid_solver.hpp
  src/solvers/thermal_operators.cpp
  src/solvers/thermal_operators.hpp
  src/solvers/thermal_solver.cpp
  src/solvers/thermal_solver.hpp
  src/solvers/thermal_structural_solver.hpp
  tests/serac_dtor.cpp
  tests/serac_dynamic_solver.cpp
  tests/serac_stdfunction_coefficient.cpp
  tests/serac_thermal_solver.cpp
  tests/serac_thermal_structural_solver.cpp
  tests/serac_wrapper_tests.cpp
Labels: CS, ready for review

#136 Encapsulate FiniteElementState in class
  src/common/CMakeLists.txt
  src/common/boundary_condition.cpp
  src/common/boundary_condition.hpp
  src/common/common.hpp
  src/common/finite_element_state.cpp
  src/common/finite_element_state.hpp
  src/common/serac_types.hpp
  src/solvers/base_solver.cpp
  src/solvers/base_solver.hpp
  src/solvers/elasticity_solver.cpp
  src/solvers/elasticity_solver.hpp
  src/solvers/nonlinear_solid_solver.cpp
  src/solvers/thermal_operators.cpp
  src/solvers/thermal_operators.hpp
  src/solvers/thermal_solver.cpp
  tests/CMakeLists.txt
  tests/mfem_array_std_algo.cpp
  tests/serac_component_bc.cpp
  tests/serac_dynamic_solver.cpp
  tests/serac_linelastic_solver.cpp
  tests/serac_quasistatic_solver.cpp
  tests/serac_thermal_solver.cpp
  tests/serac_thermal_structural_solver.cpp
Labels: CS, ready for review

#141 Add initialize function for use in drivers
  src/common/CMakeLists.txt
  src/common/common.hpp
  src/common/initialize.cpp
  src/common/initialize.hpp
  src/drivers/serac.cpp
Labels: CS, ready for review

#152 Add mail map file
  .mailmap
Labels: CS

#156 hotfix: conditionally add caliper to hostconfig
  scripts/uberenv/packages/serac/package.py
Labels: bug

#158 Add coefficient accessors to the BC class
  src/common/boundary_condition.cpp
  src/common/boundary_condition.hpp
  src/solvers/elasticity_solver.cpp
  src/solvers/nonlinear_solid_solver.cpp
Labels: CS, enhancement, ready for review

#149 Add build job on Lassen
  .gitlab-ci.yml
  .gitlab/build_lassen.yml
  .gitlab/build_quartz.yml
  host-configs/lassen-blueos_3_ppc64le_ib_p9-clang@upstream_gfortran.cmake
  scripts/gitlab/build_and_test.sh
  scripts/uberenv/project.json
  scripts/uberenv/spack_configs/blueos_3_ppc64le_ib_p9/compilers.yaml
  scripts/uberenv/spack_configs/blueos_3_ppc64le_ib_p9/devtools/packages.yaml
  scripts/uberenv/spack_configs/blueos_3_ppc64le_ib_p9/packages.yaml
Labels: CI, ready for review

#160 Fixing the ubuntu 18.04 docs
  scripts/uberenv/spack_configs/linux_ubuntu_18/compilers.yaml
  scripts/uberenv/spack_configs/linux_ubuntu_18/packages.yaml
  src/docs/index.rst
Labels: CS, documentation, ready for review

#163 Add build job for devtools on quartz
  .gitlab-ci.yml
  .gitlab/build_quartz.yml
  scripts/uberenv/spack_configs/toss_3_x86_64_ib/devtools/packages.yaml
Labels: CI, ready for review
