Repository LLNL/serac, pull requests merged in 2020-07, with the labels that each got.

#65 Operator split simple thermal-structural solver
  cmake/SeracConfigHeader.cmake
  src/coefficients/loading_functions.cpp
  src/coefficients/stdfunction_coefficient.cpp
  src/coefficients/stdfunction_coefficient.hpp
  src/coefficients/traction_coefficient.hpp
  src/common/serac_types.hpp
  src/drivers/serac.cpp
  src/integrators/hyperelastic_traction_integrator.cpp
  src/integrators/wrapper_integrator.cpp
  src/serac_config.hpp.in
  src/solvers/CMakeLists.txt
  src/solvers/base_solver.cpp
  src/solvers/base_solver.hpp
  src/solvers/elasticity_solver.cpp
  src/solvers/elasticity_solver.hpp
  src/solvers/nonlinear_solid_solver.cpp
  src/solvers/nonlinear_solid_solver.hpp
  src/solvers/thermal_solver.cpp
  src/solvers/thermal_solver.hpp
  src/solvers/thermal_structural_solver.cpp
  src/solvers/thermal_structural_solver.hpp
  tests/CMakeLists.txt
  tests/serac_component_bc.cpp
  tests/serac_dtor.cpp
  tests/serac_dynamic_solver.cpp
  tests/serac_linelastic_solver.cpp
  tests/serac_quasistatic_solver.cpp
  tests/serac_thermal_solver.cpp
  tests/serac_thermal_structural_solver.cpp
Labels: discretization, enhancement, ready for review

#81 Modify CI scripts to reflect switch to gitflow and renaming of primary branch
  .gitlab-ci.yml
  .gitlab/ci/build_quartz.yml
  README.md
  src/docs/sphinx/index.rst
Labels: CS, ready for review

#75 Use std::set instead of std::vector to indicate boundary attributes for BCs
  src/drivers/serac.cpp
  src/solvers/base_solver.cpp
  src/solvers/base_solver.hpp
  src/solvers/elasticity_solver.cpp
  src/solvers/elasticity_solver.hpp
  src/solvers/nonlinear_solid_solver.cpp
  src/solvers/nonlinear_solid_solver.hpp
  src/solvers/thermal_solver.cpp
  src/solvers/thermal_solver.hpp
  src/solvers/thermal_structural_solver.hpp
  tests/serac_component_bc.cpp
  tests/serac_dtor.cpp
  tests/serac_dynamic_solver.cpp
  tests/serac_linelastic_solver.cpp
  tests/serac_quasistatic_solver.cpp
  tests/serac_thermal_solver.cpp
  tests/serac_thermal_structural_solver.cpp
Labels: CS, ready for review

#83 Change from MFEM's command line arguments to CLI11
  src/drivers/CMakeLists.txt
  src/drivers/serac.cpp
Labels: CS, ready for review

#82 Move everything in serac_types.hpp into namespace serac
  src/common/serac_types.hpp
  src/drivers/serac.cpp
  src/solvers/base_solver.cpp
  src/solvers/base_solver.hpp
  src/solvers/elasticity_solver.cpp
  src/solvers/elasticity_solver.hpp
  src/solvers/nonlinear_solid_operators.cpp
  src/solvers/nonlinear_solid_operators.hpp
  src/solvers/nonlinear_solid_solver.cpp
  src/solvers/nonlinear_solid_solver.hpp
  src/solvers/thermal_operators.cpp
  src/solvers/thermal_operators.hpp
  src/solvers/thermal_solver.cpp
  src/solvers/thermal_solver.hpp
  src/solvers/thermal_structural_solver.cpp
  src/solvers/thermal_structural_solver.hpp
  tests/serac_component_bc.cpp
  tests/serac_dtor.cpp
  tests/serac_dynamic_solver.cpp
  tests/serac_linelastic_solver.cpp
  tests/serac_quasistatic_solver.cpp
  tests/serac_thermal_solver.cpp
  tests/serac_thermal_structural_solver.cpp
Labels: CS, ready for review

#94 Add preliminary style guide
  src/docs/sphinx/index.rst
  src/docs/sphinx/style_guide.rst
Labels: CS, documentation, ready for review

#101 Fix the typos in the readme
  README.md
Labels: bug, documentation, ready for review

#103 Fix the code style
  .clang-format
  src/coefficients/CMakeLists.txt
  src/coefficients/loading_functions.cpp
  src/coefficients/loading_functions.hpp
  src/coefficients/stdfunction_coefficient.cpp
  src/coefficients/stdfunction_coefficient.hpp
  src/coefficients/traction_coefficient.hpp
  src/common/logger.cpp
  src/common/logger.hpp
  src/docs/sphinx/style_guide.rst
  src/drivers/serac.cpp
  src/integrators/hyperelastic_traction_integrator.cpp
  src/integrators/hyperelastic_traction_integrator.hpp
  src/integrators/inc_hyperelastic_integrator.cpp
  src/integrators/inc_hyperelastic_integrator.hpp
  src/integrators/wrapper_integrator.cpp
  src/integrators/wrapper_integrator.hpp
  src/solvers/base_solver.cpp
  src/solvers/base_solver.hpp
  src/solvers/elasticity_solver.cpp
  src/solvers/elasticity_solver.hpp
  src/solvers/nonlinear_solid_operators.cpp
  src/solvers/nonlinear_solid_operators.hpp
  src/solvers/nonlinear_solid_solver.cpp
  src/solvers/nonlinear_solid_solver.hpp
  src/solvers/thermal_operators.cpp
  src/solvers/thermal_operators.hpp
  src/solvers/thermal_solver.cpp
  src/solvers/thermal_solver.hpp
  src/solvers/thermal_structural_solver.cpp
  src/solvers/thermal_structural_solver.hpp
  tests/serac_component_bc.cpp
  tests/serac_dtor.cpp
  tests/serac_dynamic_solver.cpp
  tests/serac_linelastic_solver.cpp
  tests/serac_quasistatic_solver.cpp
  tests/serac_stdfunction_coefficient.cpp
  tests/serac_thermal_solver.cpp
  tests/serac_thermal_structural_solver.cpp
  tests/serac_wrapper_tests.cpp
Labels: CS, bug, ready for review

#109 Remove the unused astyle configuration file
  astyle.cfg
Labels: CS, bug

#106 Add brief tutorial and script for creating new Docker image
  scripts/docker/build_new_image.sh
  scripts/docker/dockerfile.in
  src/docs/sphinx/docker_info.rst
  src/docs/sphinx/index.rst
Labels: documentation, ready for review

#105 Memory audit and general C++ correctness
  src/coefficients/stdfunction_coefficient.cpp
  src/coefficients/stdfunction_coefficient.hpp
  src/drivers/serac.cpp
  src/integrators/hyperelastic_traction_integrator.hpp
  src/integrators/inc_hyperelastic_integrator.hpp
  src/integrators/wrapper_integrator.hpp
  src/solvers/base_solver.cpp
  src/solvers/base_solver.hpp
  src/solvers/elasticity_solver.cpp
  src/solvers/elasticity_solver.hpp
  src/solvers/nonlinear_solid_operators.cpp
  src/solvers/nonlinear_solid_operators.hpp
  src/solvers/nonlinear_solid_solver.cpp
  src/solvers/nonlinear_solid_solver.hpp
  src/solvers/thermal_operators.hpp
  src/solvers/thermal_solver.hpp
  src/solvers/thermal_structural_solver.hpp
  tests/CMakeLists.txt
  tests/copy_elision.cpp
  tests/serac_component_bc.cpp
  tests/serac_stdfunction_coefficient.cpp
  tests/serac_wrapper_tests.cpp
Labels: CS, enhancement, ready for review
