Repository LLNL/serac, pull requests merged in 2020-09, with the labels that each got.

#166 fix: 10 more minutes for full dependency build
  .gitlab-ci.yml
Labels: CI, bug, ready for review

#177 Hardcode -cuda extension to Lassen host-config to reflect switch to CUDA-only builds
  .gitlab-ci.yml
  .gitlab/build_lassen.yml
Labels: CI, bug

#183 Resize the StdFunctionVectorCoefficient input vector
  src/coefficients/stdfunction_coefficient.cpp
Labels: bug, discretization

#184 Fix the wsl build and clarify the docs
  scripts/uberenv/spack_configs/linux_ubuntu_20/compilers.yaml
  src/docs/index.rst
Labels: CS, bug, documentation, ready for review

#178 Delete Azure and Gitlab "build_and_test" scripts
  .gitlab-ci.yml
  .gitlab/build_lassen.yml
  .gitlab/build_quartz.yml
  azure-pipelines.yml
  scripts/azure-pipelines/linux-build_and_test.sh
  scripts/gitlab/build_and_test.sh
  scripts/llnl/build_src.py
  scripts/llnl/common_build_functions.py
Labels: CI

#173 Add an option for direct solver with SuperLU
  src/common/serac_types.hpp
  src/solvers/equation_solver.cpp
  src/solvers/equation_solver.hpp
  src/solvers/nonlinear_solid_operators.cpp
  src/solvers/nonlinear_solid_operators.hpp
  src/solvers/nonlinear_solid_solver.cpp
  src/solvers/thermal_operators.cpp
  src/solvers/thermal_solver.cpp
  tests/serac_dynamic_solver.cpp
  tests/serac_quasistatic_solver.cpp
  tests/serac_thermal_solver.cpp
Labels: discretization, enhancement

#169 Encapsulate all boundary conditions in a separate class
  src/common/CMakeLists.txt
  src/common/boundary_condition.hpp
  src/common/boundary_condition_manager.cpp
  src/common/boundary_condition_manager.hpp
  src/common/common.hpp
  src/solvers/base_solver.cpp
  src/solvers/base_solver.hpp
  src/solvers/elasticity_solver.cpp
  src/solvers/nonlinear_solid_operators.cpp
  src/solvers/nonlinear_solid_operators.hpp
  src/solvers/nonlinear_solid_solver.cpp
  src/solvers/thermal_operators.cpp
  src/solvers/thermal_operators.hpp
  src/solvers/thermal_solver.cpp
  tests/CMakeLists.txt
  tests/serac_boundary_cond.cpp
Labels: CS, enhancement, ready for review

#159 Add an export that allows for completely out-of-source use of Serac
  CMakeLists.txt
  cmake/SeracConfigHeader.cmake
  cmake/serac-config.cmake.in
  config-build.py
  examples/CMakeLists.txt
  examples/host-config.cmake.in
  examples/using-with-cmake/CMakeLists.txt
  examples/using-with-cmake/serac_example.cpp
  scripts/llnl/common_build_functions.py
  src/coefficients/CMakeLists.txt
  src/common/CMakeLists.txt
  src/docs/index.rst
  src/drivers/CMakeLists.txt
  src/integrators/CMakeLists.txt
  src/solvers/CMakeLists.txt
  tests/CMakeLists.txt
Labels: CS, ready for review

#201 Build dependencies out-of-source
  .gitlab-ci.yml
  .gitlab/build_quartz.yml
  scripts/llnl/common_build_functions.py
Labels: CI

#207 Switch to Google Benchmark for expression template benchmarking
  CMakeLists.txt
  src/numerics/vector_expression.hpp
  tests/CMakeLists.txt
  tests/benchmark_expr_templates.cpp
  tests/expr_templates.cpp
Labels: CS, ready for review

#213 Fix operator precedence warnings, add support for HypreParVector expr templates
  src/docs/sphinx/expr_templates.rst
  src/numerics/expr_template_internal.hpp
  src/numerics/expr_template_ops.hpp
  src/numerics/vector_expression.hpp
  tests/benchmark_expr_templates.cpp
  tests/expr_templates.cpp
Labels: CS
