Repository LLNL/serac, pull requests merged in 2020-03, with the labels that each got.

#3 Adding readthedocs and sphinx documentation
  .readthedocs.yml
  README.md
  src/docs/sphinx/conf.py
  src/docs/sphinx/index.rst
Labels: documentation

#4 Linear elastic solver
  src/common/serac_types.hpp
  src/solvers/CMakeLists.txt
  src/solvers/base_solver.cpp
  src/solvers/base_solver.hpp
  src/solvers/elasticity_solver.cpp
  src/solvers/elasticity_solver.hpp
  src/solvers/linear_elasticity_solver.cpp
  src/solvers/linear_elasticity_solver.hpp
  src/solvers/thermal_solver.cpp
  tests/serac_linelastic_solver.cpp
Labels: enhancement

#5 Hyperelastic solver object
  .gitignore
  .vscode/c_cpp_properties.json
  .vscode/launch.json
  CONTRIBUTING.md
  scripts/uberenv/spack_configs/linux-ubuntu18.04-broadwell/compilers.yaml
  scripts/uberenv/spack_configs/linux-ubuntu18.04-broadwell/packages.yaml
  src/common/serac_types.hpp
  src/docs/CMakeLists.txt
  src/drivers/serac.cpp
  src/solvers/CMakeLists.txt
  src/solvers/base_solver.cpp
  src/solvers/base_solver.hpp
  src/solvers/dynamic_solver.cpp
  src/solvers/dynamic_solver.hpp
  src/solvers/nonlinear_solid_solver.cpp
  src/solvers/nonlinear_solid_solver.hpp
  src/solvers/quasistatic_solver.cpp
  src/solvers/quasistatic_solver.hpp
  tests/serac_dynamic_solver.cpp
  tests/serac_quasistatic_solver.cpp
  tests/serac_thermal_solver.cpp
Labels: discretization, enhancement, ready for review

#33 Fixing the wsl build to enable clang and vscode support
  .vscode/c_cpp_properties.json
  .vscode/cmake-kits.json
  .vscode/launch.json
  .vscode/settings.json
  scripts/uberenv/spack_configs/linux-ubuntu18.04-broadwell/compilers.yaml
  src/coefficients/stdfunction_coefficient.cpp
Labels: CS, enhancement

#36 Fixing serac CI on Gitlab: back to the basics [fix/ci]
  .gitlab-ci.yml
  .gitlab/ci/build_quartz.yml
  scripts/gitlab/build_and_test.sh
Labels: bug
