Repository LLNL/serac, pull requests merged in 2020-10, with the labels that each got.

#227 Increasing the TPL build allocation time
  .gitlab-ci.yml
  CONTRIBUTING.md
Labels: CI, bug

#234 Adds developer documentation to readthedocs
  src/docs/index.rst
  src/docs/sphinx/developer_guide.rst
Labels: documentation, ready for review

#199 Add an optional clang-tidy check
  cmake/SeracMacros.cmake
  host-configs/lassen-blueos_3_ppc64le_ib_p9-clang@upstream_gfortran-cuda.cmake
  host-configs/quartz-toss_3_x86_64_ib-clang@10.0.0.cmake
  host-configs/quartz-toss_3_x86_64_ib-gcc@8.3.1.cmake
  host-configs/rzansel-blueos_3_ppc64le_ib_p9-clang@upstream_gfortran-cuda.cmake
  host-configs/rzgenie-toss_3_x86_64_ib-clang@10.0.0.cmake
  host-configs/rzgenie-toss_3_x86_64_ib-gcc@8.3.1.cmake
  scripts/uberenv/packages/serac/package.py
  src/infrastructure/initialize.cpp
  src/infrastructure/initialize.hpp
  src/infrastructure/logger.cpp
  src/infrastructure/terminator.cpp
  src/integrators/inc_hyperelastic_integrator.cpp
  src/physics/base_physics.cpp
  src/physics/base_physics.hpp
  src/physics/nonlinear_solid.cpp
  tests/copy_elision.cpp
  tests/serac_stdfunction_coefficient.cpp
  tests/serac_wrapper_tests.cpp
Labels: CS, ready for review

#235 Add link to tests directory
  src/docs/sphinx/developer_guide.rst
Labels: bug, documentation, ready for review

#240 Fix pulling exact commits for external repos
  scripts/uberenv/packages/axom/package.py
  scripts/uberenv/packages/conduit/package.py
  scripts/uberenv/packages/mfem/package.py
  tests/serac_dynamic_solver.cpp
Labels: bug, build, ready for review

#233 Automate the docker image builds
  .github/workflows/docker_build_tpls.yml
  scripts/docker/build_new_dockerfile.sh
  scripts/docker/dockerfile.in
  scripts/docker/dockerfile_clang-10
  scripts/docker/dockerfile_clang-6
  scripts/docker/dockerfile_fake
  scripts/docker/dockerfile_gcc-8
  scripts/uberenv/spack_configs/docker/ubuntu16/compilers.yaml
  scripts/uberenv/spack_configs/docker/ubuntu16/packages.yaml
  scripts/uberenv/spack_configs/docker/ubuntu18/packages.yaml
  src/docs/sphinx/docker_info.rst
  src/docs/sphinx/expr_templates.rst
Labels: CI

#245 Add timestamps to Docker image tags
  .github/workflows/docker_build_tpls.yml
Labels: CI, ready for review

#247 [DISCUSS] Add small overview of modern C++ features utilized in Serac + references
  src/docs/sphinx/developer_guide.rst
Labels: documentation

#208 Added preliminary change of variables integrator
  src/integrators/wrapper_integrator.cpp
  src/integrators/wrapper_integrator.hpp
  tests/serac_wrapper_tests.cpp
Labels: discretization, ready for review

#88 Add SidreDataCollection as an output option
  scripts/uberenv/packages/axom/package.py
  scripts/uberenv/packages/serac/package.py
  scripts/uberenv/spack_configs/docker/ubuntu18/compilers.yaml
  src/physics/base_physics.cpp
  src/physics/utilities/solver_config.hpp
Labels: CS, ready for review

#261 Fix some minor AMG and const issues
  src/physics/elasticity.cpp
  src/physics/nonlinear_solid.cpp
  src/physics/operators/nonlinear_solid_operators.cpp
  src/physics/operators/thermal_operators.cpp
  src/physics/utilities/boundary_condition_manager.hpp
  src/physics/utilities/equation_solver.cpp
  src/physics/utilities/equation_solver.hpp
  src/physics/utilities/solver_config.hpp
  tests/serac_thermal_solver.cpp
Labels: CS, bug
