Repository LLNL/serac, pull requests merged in 2020-11, with the labels that each got.

#265 update axom spack package
  scripts/uberenv/packages/axom/package.py
Labels: TPL, bug, build

#277 Submodule conflicts
  cmake/SeracMacros.cmake
  cmake/thirdparty/SetupSeracThirdParty.cmake
  examples/host-config.cmake.in
  examples/using-with-cmake/CMakeLists.txt
  src/drivers/CMakeLists.txt
  src/drivers/serac.cpp
  src/infrastructure/cli.cpp
  src/infrastructure/cli.hpp
  tests/CMakeLists.txt
Labels: CS, build, ready for review

#254 Integrate MFEM's CUDA support into serac + AMGX, merge in changes from MFEM spack package
  .gitlab-ci.yml
  azure-pipelines.yml
  cmake/thirdparty/FindMFEM.cmake
  host-configs/docker/docker-linux-ubuntu16.04-x86_64-gcc@8.1.0.cmake
  host-configs/docker/docker-linux-ubuntu18.04-x86_64-clang@10.0.0.cmake
  host-configs/lassen-blueos_3_ppc64le_ib_p9-clang@upstream_gfortran-cuda.cmake
  host-configs/quartz-toss_3_x86_64_ib-clang@10.0.0.cmake
  host-configs/quartz-toss_3_x86_64_ib-gcc@8.3.1.cmake
  host-configs/rzansel-blueos_3_ppc64le_ib_p9-clang@ibm_gfortran-cuda.cmake
  host-configs/rzansel-blueos_3_ppc64le_ib_p9-clang@upstream_gfortran-cuda.cmake
  host-configs/rzgenie-toss_3_x86_64_ib-clang@10.0.0.cmake
  host-configs/rzgenie-toss_3_x86_64_ib-gcc@8.3.1.cmake
  scripts/llnl/build_tpls.py
  scripts/llnl/common_build_functions.py
  scripts/uberenv/packages/amgx/package.py
  scripts/uberenv/packages/axom/package.py
  scripts/uberenv/packages/mfem/package.py
  scripts/uberenv/packages/serac/package.py
  scripts/uberenv/spack_configs/blueos_3_ppc64le_ib_p9/packages.yaml
  src/infrastructure/CMakeLists.txt
  src/infrastructure/accelerator.cpp
  src/infrastructure/accelerator.hpp
  src/infrastructure/initialize.cpp
  src/infrastructure/terminator.cpp
  src/physics/nonlinear_solid.cpp
  src/physics/utilities/equation_solver.cpp
  src/physics/utilities/solver_config.hpp
  tests/serac_dynamic_solver.cpp
Labels: enhancement, ready for review

#286 Small WSL build fixes
  scripts/uberenv/spack_configs/linux_ubuntu_18/compilers.yaml
  src/docs/index.rst
Labels: bug, build
