Repository LLNL/serac, pull requests merged in 2020-12, with the labels that each got.

#294 Make the quasi-static operator definitions overrideable
  src/physics/nonlinear_solid.cpp
  src/physics/nonlinear_solid.hpp
Labels: bug, discretization

#295 Move most of ODE logic into TimeDependentOperator wrappers
  src/physics/base_physics.cpp
  src/physics/base_physics.hpp
  src/physics/nonlinear_solid.cpp
  src/physics/nonlinear_solid.hpp
  src/physics/operators/CMakeLists.txt
  src/physics/operators/odes.cpp
  src/physics/operators/odes.hpp
  src/physics/thermal_conduction.cpp
  src/physics/thermal_conduction.hpp
  src/physics/thermal_solid.cpp
  src/physics/thermal_solid.hpp
  src/physics/utilities/equation_solver.hpp
Labels: discretization, ready for review

#296 Add fake mpi target to using-with-cmake example
  examples/using-with-cmake/CMakeLists.txt
Labels: build

#297 Move ODE solver into ODE class
  src/drivers/serac.cpp
  src/physics/base_physics.cpp
  src/physics/base_physics.hpp
  src/physics/elasticity.cpp
  src/physics/nonlinear_solid.cpp
  src/physics/operators/odes.cpp
  src/physics/operators/odes.hpp
  src/physics/thermal_conduction.cpp
  src/physics/thermal_conduction.hpp
  src/physics/thermal_solid.cpp
  src/physics/thermal_solid.hpp
Labels: ready for review, refactoring

#299 Replace c0 with c1 in SecondOrderODE where appropriate due to previous typos
  src/physics/operators/odes.cpp
Labels: bug

#318 TPL setup problems
  cmake/thirdparty/SetupSeracThirdParty.cmake
Labels: CS, TPL, build, ready for review
