Repository LLNL/serac, pull requests merged in 2021-08, with the labels that each got.

#519 Material parameter sensitivities
  src/serac/coefficients/CMakeLists.txt
  src/serac/coefficients/sensitivity_coefficients.cpp
  src/serac/coefficients/sensitivity_coefficients.hpp
  src/serac/physics/CMakeLists.txt
  src/serac/physics/materials/hyperelastic_material.cpp
  src/serac/physics/materials/hyperelastic_material.hpp
  src/serac/physics/solid.cpp
  src/serac/physics/solid.hpp
  src/serac/physics/tests/serac_solid_adjoint.cpp
Labels: discretization, ready for review

#525 Output curve field data
  .gitlab/build_quartz.yml
  src/drivers/serac.cpp
  src/serac/infrastructure/initialize.cpp
  src/serac/infrastructure/initialize.hpp
  src/serac/infrastructure/output.cpp
  src/serac/infrastructure/output.hpp
  src/serac/physics/base_physics.cpp
  src/serac/physics/base_physics.hpp
  src/serac/physics/utilities/finite_element_state.cpp
  src/serac/physics/utilities/finite_element_state.hpp
Labels: output, ready for review

#534 Use correct type in `avg` function MPI call
  src/serac/physics/utilities/finite_element_state.cpp
Labels: CS, bug, ready for review

#541 Add the nested test directories to the code checks
  cmake/SeracMacros.cmake
Labels: ready for review, build

#546 Handle recent SLURM update
  .gitlab/build_quartz.yml
Labels: bug, CS, CI

#545 Fix the doxygen
  src/docs/doxygen/Doxyfile.in
  src/docs/doxygen/mainpage.md
  src/serac/numerics/assembled_sparse_matrix.cpp
  src/serac/physics/solid.hpp
  src/serac/physics/utilities/functional/boundary_integral.hpp
  src/serac/physics/utilities/functional/detail/metaprogramming.hpp
  src/serac/physics/utilities/functional/domain_integral.hpp
  src/serac/physics/utilities/functional/functional.hpp
  src/serac/physics/utilities/functional/integral_utilities.hpp
  src/serac/physics/utilities/quadrature_data.hpp
  src/serac/physics/utilities/state_manager.cpp
  src/serac/physics/utilities/state_manager.hpp
  src/serac/physics/utilities/variant.hpp
Labels: documentation, ready for review

#544 Remove the extra adjoint solve warning.
  src/serac/physics/solid.cpp
Labels: discretization, ready for review

#527 Enable all output to go to a directory
  src/docs/conf.py
  src/docs/sphinx/user_guide/command_line_options.rst
  src/docs/sphinx/user_guide/index.rst
  src/drivers/CMakeLists.txt
  src/drivers/serac.cpp
  src/serac/infrastructure/cli.cpp
  src/serac/infrastructure/input.cpp
  src/serac/infrastructure/input.hpp
  src/serac/infrastructure/logger.cpp
  src/serac/infrastructure/output.cpp
  src/serac/infrastructure/output.hpp
  src/serac/physics/base_physics.cpp
  src/serac/physics/base_physics.hpp
  src/serac/physics/tests/test_utilities.cpp
  src/serac/physics/utilities/functional/tests/functional_material_state_test.cpp
  src/serac/physics/utilities/state_manager.cpp
  src/serac/physics/utilities/state_manager.hpp
Labels: CS, ready for review, output
