Repository LLNL/serac, pull requests merged in 2021-07, with the labels that each got.

#494 Add QuadratureData class for encapsulating quadrature point data
  scripts/llnl/common_build_functions.py
  src/serac/physics/utilities/CMakeLists.txt
  src/serac/physics/utilities/boundary_condition.cpp
  src/serac/physics/utilities/finite_element_state.cpp
  src/serac/physics/utilities/finite_element_state.hpp
  src/serac/physics/utilities/functional/boundary_integral.hpp
  src/serac/physics/utilities/functional/functional.hpp
  src/serac/physics/utilities/functional/integral.hpp
  src/serac/physics/utilities/functional/tests/CMakeLists.txt
  src/serac/physics/utilities/functional/tests/functional_material_state_test.cpp
  src/serac/physics/utilities/quadrature_data.hpp
  src/serac/physics/utilities/state_manager.cpp
  src/serac/physics/utilities/state_manager.hpp
  src/serac/physics/utilities/variant.hpp
Labels: CS, enhancement, ready for review

#512 Update to Conduit 0.7.2
  CMakeLists.txt
  azure-pipelines.yml
  cmake/serac-config.cmake.in
  cmake/thirdparty/SetupSeracThirdParty.cmake
  examples/using-with-cmake/CMakeLists.txt
  host-configs/docker/docker-linux-ubuntu20.04-ivybridge-clang@10.0.0.cmake
  host-configs/docker/docker-linux-ubuntu20.04-ivybridge-gcc@9.3.0.cmake
  host-configs/lassen-blueos_3_ppc64le_ib_p9-clang@10.0.1.cmake
  host-configs/quartz-toss_3_x86_64_ib-clang@10.0.0.cmake
  host-configs/quartz-toss_3_x86_64_ib-gcc@8.3.1.cmake
  host-configs/rzansel-blueos_3_ppc64le_ib_p9-clang@10.0.1.cmake
  host-configs/rzgenie-toss_3_x86_64_ib-clang@10.0.0.cmake
  host-configs/rzgenie-toss_3_x86_64_ib-gcc@8.3.1.cmake
  scripts/spack/configs/blueos_3_ppc64le_ib_p9/packages.yaml
  scripts/spack/packages/conduit/fj_flags.patch
  scripts/spack/packages/conduit/package.py
  scripts/spack/packages/serac/package.py
Labels: CS, TPL, build, install, ready for review

#492 `Functional`: add support for surface integrals
  data/meshes/twosquare.mesh
  src/serac/physics/utilities/functional/boundary_integral.hpp
  src/serac/physics/utilities/functional/detail/hexahedron_L2.inl
  src/serac/physics/utilities/functional/detail/quadrilateral_L2.inl
  src/serac/physics/utilities/functional/detail/segment_H1.inl
  src/serac/physics/utilities/functional/detail/segment_L2.inl
  src/serac/physics/utilities/functional/domain_integral.hpp
  src/serac/physics/utilities/functional/functional.hpp
  src/serac/physics/utilities/functional/integral_utilities.hpp
  src/serac/physics/utilities/functional/quadrature.hpp
  src/serac/physics/utilities/functional/tests/CMakeLists.txt
  src/serac/physics/utilities/functional/tests/functional_boundary_test.cpp
  src/serac/physics/utilities/functional/tests/functional_comparison_L2.cpp
  src/serac/physics/utilities/functional/tests/performance/diffusion_performance_test.cpp
  src/serac/physics/utilities/functional/tests/performance/kernel_microbenchmark.cpp
Labels: enhancement, ready for review

#516 Turn back on style checks in CI
  azure-pipelines.yml
  scripts/azure-pipelines/linux-check.sh
  scripts/docker/dockerfile_clang-10
Labels: CI, CS, bug, ready for review

#501 Add adjoint solve options to the solid module
  src/serac/physics/solid.cpp
  src/serac/physics/solid.hpp
  src/serac/physics/utilities/boundary_condition.cpp
  src/serac/physics/utilities/finite_element_state.cpp
  src/serac/physics/utilities/finite_element_state.hpp
  tests/CMakeLists.txt
  tests/serac_solid_adjoint.cpp
Labels: discretization, ready for review

#515 Test reorganization
  cmake/serac-config.cmake.in
  cmake/thirdparty/SetupSeracThirdParty.cmake
  src/serac/coefficients/CMakeLists.txt
  src/serac/coefficients/tests/CMakeLists.txt
  src/serac/coefficients/tests/serac_component_bc.cpp
  src/serac/infrastructure/CMakeLists.txt
  src/serac/infrastructure/tests/CMakeLists.txt
  src/serac/infrastructure/tests/serac_error_handling.cpp
  src/serac/infrastructure/tests/serac_input.cpp
  src/serac/infrastructure/tests/serac_profiling.cpp
  src/serac/numerics/CMakeLists.txt
  src/serac/numerics/tests/CMakeLists.txt
  src/serac/numerics/tests/benchmark_expr_templates.cpp
  src/serac/numerics/tests/expr_templates.cpp
  src/serac/numerics/tests/mesh_generation.cpp
  src/serac/numerics/tests/serac_mesh.cpp
  src/serac/physics/CMakeLists.txt
  src/serac/physics/integrators/CMakeLists.txt
  src/serac/physics/integrators/tests/CMakeLists.txt
  src/serac/physics/integrators/tests/serac_wrapper_tests.cpp
  src/serac/physics/operators/CMakeLists.txt
  src/serac/physics/operators/tests/CMakeLists.txt
  src/serac/physics/operators/tests/serac_odes.cpp
  src/serac/physics/operators/tests/serac_operator.cpp
  src/serac/physics/tests/CMakeLists.txt
  src/serac/physics/tests/serac_boundary_cond.cpp
  src/serac/physics/tests/serac_dtor.cpp
  src/serac/physics/tests/serac_newmark_test.cpp
  src/serac/physics/tests/serac_solid.cpp
  src/serac/physics/tests/serac_solid_adjoint.cpp
  src/serac/physics/tests/serac_solid_reuse_mesh.cpp
  src/serac/physics/tests/serac_thermal_solver.cpp
  src/serac/physics/tests/serac_thermal_structural_solver.cpp
  src/serac/physics/tests/test_utilities.cpp
  src/serac/physics/tests/test_utilities.hpp
  src/serac/physics/utilities/functional/CMakeLists.txt
  src/serac/physics/utilities/functional/tests/CMakeLists.txt
  tests/CMakeLists.txt
Labels: build, ready for review, refactoring

#521 Fix full lassen build
  .gitlab-ci.yml
  .gitlab/build_lassen.yml
  .gitlab/build_quartz.yml
  scripts/spack/packages/serac/package.py
Labels: CI, CS, TPL, bug, build, gpu, invalid, ready for review

#522 Add a testing cmake macro
  cmake/SeracMacros.cmake
  src/serac/coefficients/tests/CMakeLists.txt
  src/serac/infrastructure/tests/CMakeLists.txt
  src/serac/numerics/tests/CMakeLists.txt
  src/serac/physics/integrators/tests/CMakeLists.txt
  src/serac/physics/operators/tests/CMakeLists.txt
  src/serac/physics/tests/CMakeLists.txt
  src/serac/physics/utilities/functional/tests/CMakeLists.txt
  tests/CMakeLists.txt
Labels: CS, build

#524 Fix parallel driver
  src/drivers/CMakeLists.txt
  src/serac/infrastructure/output.cpp
Labels: CS, bug

#530 Install Functional's implementation headers to detail directory
  src/serac/physics/utilities/functional/CMakeLists.txt
Labels: bug, build, ready for review
