Repository LLNL/serac, pull requests merged in 2021-06, with the labels that each got.

#477 add support for q-function interface with discontinuous Galerkin fields
  src/serac/physics/utilities/functional/CMakeLists.txt
  src/serac/physics/utilities/functional/detail/hexahedron_H1.inl
  src/serac/physics/utilities/functional/detail/hexahedron_Hcurl.inl
  src/serac/physics/utilities/functional/detail/hexahedron_L2.inl
  src/serac/physics/utilities/functional/detail/quadrilateral_H1.inl
  src/serac/physics/utilities/functional/detail/quadrilateral_Hcurl.inl
  src/serac/physics/utilities/functional/detail/quadrilateral_L2.inl
  src/serac/physics/utilities/functional/detail/segment_H1.inl
  src/serac/physics/utilities/functional/detail/segment_Hcurl.inl
  src/serac/physics/utilities/functional/detail/segment_L2.inl
  src/serac/physics/utilities/functional/finite_element.hpp
  src/serac/physics/utilities/functional/integral.hpp
  src/serac/physics/utilities/functional/polynomials.hpp
  src/serac/physics/utilities/functional/quadrature.hpp
  src/serac/physics/utilities/functional/tests/CMakeLists.txt
  src/serac/physics/utilities/functional/tests/functional_comparison_L2.cpp
  src/serac/physics/utilities/functional/tests/functional_comparisons.cpp
  src/serac/physics/utilities/functional/tests/l2_comparison.cpp
  src/serac/physics/utilities/functional/tests/performance/J2_material_with_AD.cpp
  src/serac/physics/utilities/functional/tests/performance/diffusion_performance_test.cpp
Labels: discretization, enhancement, ready for review

#479 Doxygen improvements and warnings
  src/docs/doxygen/Doxyfile.in
  src/docs/doxygen/mainpage.md
  src/docs/sphinx/dev_guide/logging.rst
  src/docs/sphinx/dev_guide/mfem_dev.rst
  src/docs/sphinx/dev_guide/modern_cpp.rst
  src/serac/coefficients/coefficient_extensions.hpp
  src/serac/infrastructure/accelerator.hpp
  src/serac/infrastructure/input.hpp
  src/serac/infrastructure/profiling.cpp
  src/serac/infrastructure/profiling.hpp
  src/serac/infrastructure/terminator.hpp
  src/serac/numerics/expr_template_ops.hpp
  src/serac/numerics/mesh_utils.cpp
  src/serac/numerics/mesh_utils.hpp
  src/serac/physics/base_physics.hpp
  src/serac/physics/solid.cpp
  src/serac/physics/solid.hpp
  src/serac/physics/thermal_conduction.cpp
  src/serac/physics/thermal_conduction.hpp
  src/serac/physics/utilities/equation_solver.cpp
  src/serac/physics/utilities/equation_solver.hpp
  src/serac/physics/utilities/finite_element_state.hpp
  src/serac/physics/utilities/functional/polynomials.hpp
Labels: documentation, enhancement, good first issue, gpu, invalid

#487 Add link to MFEM to the readme and sphinx landing page
  README.md
  src/docs/index.rst
Labels: documentation, ready for review

#490 Update the ubuntu 18 package config file
  scripts/spack/configs/linux_ubuntu_18/packages.yaml
Labels: TPL, ready for review

#478 Add profiling tags to functional_comparisons test
  src/serac/infrastructure/profiling.hpp
  src/serac/physics/utilities/functional/CMakeLists.txt
  src/serac/physics/utilities/functional/tensor.hpp
  src/serac/physics/utilities/functional/tests/functional_comparison_L2.cpp
  src/serac/physics/utilities/functional/tests/functional_comparisons.cpp
  src/serac/physics/utilities/functional/tests/performance/J2_material_with_AD.cpp
  src/serac/physics/utilities/functional/tests/tensor_unit_tests.cpp
  src/serac/physics/utilities/functional/tests/tuple_arithmetic_unit_tests.cpp
Labels: gpu, ready for review

#484 Functional feature: Computes matrix entries for H1/Hcurl
  src/serac/numerics/CMakeLists.txt
  src/serac/numerics/assembled_sparse_matrix.cpp
  src/serac/numerics/assembled_sparse_matrix.hpp
  src/serac/physics/utilities/functional/detail/metaprogramming.hpp
  src/serac/physics/utilities/functional/functional.hpp
  src/serac/physics/utilities/functional/integral.hpp
  src/serac/physics/utilities/functional/tensor.hpp
  src/serac/physics/utilities/functional/tests/functional_comparisons.cpp
Labels: ready for review

#497 StateManager
  examples/simple_conduction/with_input_file.cpp
  examples/simple_conduction/without_input_file.cpp
  src/docs/sphinx/user_guide/simple_conduction_tutorial.rst
  src/drivers/serac.cpp
  src/serac/infrastructure/output.cpp
  src/serac/infrastructure/output.hpp
  src/serac/physics/base_physics.cpp
  src/serac/physics/solid.cpp
  src/serac/physics/thermal_conduction.cpp
  src/serac/physics/utilities/CMakeLists.txt
  src/serac/physics/utilities/finite_element_state.cpp
  src/serac/physics/utilities/finite_element_state.hpp
  src/serac/physics/utilities/state_manager.cpp
  src/serac/physics/utilities/state_manager.hpp
  tests/serac_component_bc.cpp
  tests/serac_dtor.cpp
  tests/serac_error_handling.cpp
  tests/serac_newmark_test.cpp
  tests/serac_solid.cpp
  tests/serac_solid_reuse_mesh.cpp
  tests/serac_thermal_solver.cpp
  tests/serac_thermal_structural_solver.cpp
  tests/test_utilities.cpp
Labels: CS

#503 Add a norm convenience function
  src/serac/physics/utilities/finite_element_state.cpp
  src/serac/physics/utilities/finite_element_state.hpp
  tests/serac_component_bc.cpp
  tests/serac_solid.cpp
  tests/serac_solid_reuse_mesh.cpp
  tests/serac_thermal_structural_solver.cpp
  tests/test_utilities.cpp
Labels: discretization, ready for review

#502 Move NVCC-incompatible variant stuff in mesh_utils
  src/serac/numerics/CMakeLists.txt
  src/serac/numerics/mesh_utils.hpp
  src/serac/numerics/mesh_utils_base.hpp
  src/serac/physics/utilities/functional/tests/functional_comparison_L2.cpp
  src/serac/physics/utilities/functional/tests/functional_comparisons.cpp
Labels: CS, bug, gpu, ready for review
