Repository LLNL/serac, pull requests merged in 2021-01, with the labels that each got.

#325 Add links to doxygen
  README.md
  src/docs/index.rst
Labels: documentation, ready for review

#315 Fix the WSL/Ubuntu/GCC-9 TPL builds
  scripts/spack/packages/netcdf-c/package.py
Labels: TPL, bug, build

#330 Use a relative path for uberenv
  scripts/llnl/common_build_functions.py
Labels: CS, build, ready for review

#332 Update README.md
  README.md
Labels: documentation, enhancement

#323 Add input schemas/test files for thermal solver
  data/input_files/tests/nonlinear_solid/dyn_amgx_solve.lua
  data/input_files/tests/nonlinear_solid/dyn_direct_solve.lua
  data/input_files/tests/nonlinear_solid/dyn_linesearch_solve.lua
  data/input_files/tests/nonlinear_solid/dyn_solve.lua
  data/input_files/tests/nonlinear_solid/qs_attribute_solve.lua
  data/input_files/tests/nonlinear_solid/qs_component_solve.lua
  data/input_files/tests/nonlinear_solid/qs_direct_solve.lua
  data/input_files/tests/nonlinear_solid/qs_solve.lua
  data/input_files/tests/thermal_conduction/dyn_exp_solve.lua
  data/input_files/tests/thermal_conduction/dyn_imp_solve.lua
  data/input_files/tests/thermal_conduction/static_amgx_solve.lua
  data/input_files/tests/thermal_conduction/static_solve.lua
  data/input_files/tests/thermal_conduction/static_solve_multiple_bcs.lua
  data/input_files/tests/thermal_conduction/static_solve_repeated_bcs.lua
  src/serac/infrastructure/input.cpp
  src/serac/physics/nonlinear_solid.cpp
  src/serac/physics/nonlinear_solid.hpp
  src/serac/physics/thermal_conduction.cpp
  src/serac/physics/thermal_conduction.hpp
  src/serac/physics/utilities/equation_solver.cpp
  tests/CMakeLists.txt
  tests/serac_component_bc.cpp
  tests/serac_input.cpp
  tests/serac_nonlinear_solid.cpp
  tests/serac_thermal_solver.cpp
  tests/test_utilities.cpp
  tests/test_utilities.hpp
Labels: CS

#351 Adds shadow errors to the build system
  cmake/SeracCompilerFlags.cmake
  src/serac/physics/operators/odes.cpp
  src/serac/physics/operators/odes.hpp
  src/serac/physics/utilities/equation_solver.cpp
  tests/expr_templates.cpp
  tests/serac_odes.cpp
  tests/serac_thermal_structural_solver.cpp
  tests/serac_wrapper_tests.cpp
Labels: build, ready for review

#241 Implements a second order time integrator that uses mfem::NewmarkSolver.
  data/input_files/tests/meshing/meshing.lua
  data/input_files/tests/nonlinear_solid/dyn_newmark_solve.lua
  data/input_files/tests/nonlinear_solid/dyn_newmark_solve_bending.lua
  data/input_files/tests/nonlinear_solid/dyn_newmark_solve_bending_first.lua
  src/serac/infrastructure/input.cpp
  src/serac/integrators/wrapper_integrator.hpp
  src/serac/numerics/mesh_utils.cpp
  src/serac/physics/nonlinear_solid.cpp
  src/serac/physics/operators/odes.cpp
  src/serac/physics/operators/odes.hpp
  tests/CMakeLists.txt
  tests/mesh_generation.cpp
  tests/serac_newmark_test.cpp
Labels: discretization, ready for review
