Repository LLNL/serac, pull requests merged in 2021-02, with the labels that each got.

#329 Add instructions on using a Docker image for development
  .github/workflows/docker_build_tpls.yml
  azure-pipelines.yml
  scripts/docker/dockerfile.in
  scripts/docker/dockerfile_clang-10
  scripts/docker/dockerfile_gcc-8
  src/docs/index.rst
  src/docs/sphinx/dev_guide/copy_pull_cmd.png
  src/docs/sphinx/dev_guide/docker_dev_env.rst
  src/docs/sphinx/dev_guide/index.rst
  src/docs/sphinx/dev_guide/new_docker_image.rst
  src/docs/sphinx/dev_guide/pull_complete.png
  src/docs/sphinx/user_guide/index.rst
Labels: build, documentation

#379 Re-add the accidentally deleted cylinder tests
  src/serac/numerics/mesh_utils.cpp
  tests/mesh_generation.cpp
Labels: CI, bug

#349 Change the default finite element state to be scalar-valued
  src/serac/physics/elasticity.cpp
  src/serac/physics/nonlinear_solid.cpp
  src/serac/physics/thermal_conduction.cpp
  src/serac/physics/utilities/finite_element_state.cpp
  src/serac/physics/utilities/finite_element_state.hpp
Labels: discretization, enhancement, ready for review

#360 Switch to Python3 in GitLab CI
  .gitlab-ci.yml
  scripts/llnl/common_build_functions.py
Labels: CI, build, ready for review

#382 hotfix: push back AMGX to specific commit
  host-configs/lassen-blueos_3_ppc64le_ib_p9-clang@10.0.1-cuda.cmake
  host-configs/rzansel-blueos_3_ppc64le_ib_p9-clang@10.0.1-cuda.cmake
  scripts/spack/packages/amgx/package.py
Labels: TPL, bug, ready for review

#386 Adding constant coefficient input options
  data/input_files/default.lua
  data/input_files/tests/nonlinear_solid/dyn_amgx_solve.lua
  data/input_files/tests/nonlinear_solid/dyn_direct_solve.lua
  data/input_files/tests/nonlinear_solid/dyn_linesearch_solve.lua
  data/input_files/tests/nonlinear_solid/dyn_newmark_solve.lua
  data/input_files/tests/nonlinear_solid/dyn_newmark_solve_bending.lua
  data/input_files/tests/nonlinear_solid/dyn_newmark_solve_bending_first.lua
  data/input_files/tests/nonlinear_solid/dyn_solve.lua
  data/input_files/tests/nonlinear_solid/qs_attribute_solve.lua
  data/input_files/tests/nonlinear_solid/qs_component_solve.lua
  data/input_files/tests/nonlinear_solid/qs_direct_solve.lua
  data/input_files/tests/nonlinear_solid/qs_solve.lua
  data/input_files/tests/thermal_conduction/dyn_exp_solve.lua
  data/input_files/tests/thermal_conduction/dyn_imp_solve.lua
  data/input_files/tests/thermal_conduction/static_amgx_solve.lua
  data/input_files/tests/thermal_conduction/static_solve.lua
  data/input_files/tests/thermal_conduction/static_solve_multiple_bcs.lua
  data/input_files/tests/thermal_conduction/static_solve_repeated_bcs.lua
  src/drivers/serac.cpp
  src/serac/coefficients/CMakeLists.txt
  src/serac/coefficients/traction_coefficient.hpp
  src/serac/infrastructure/input.cpp
  src/serac/infrastructure/input.hpp
  src/serac/numerics/mesh_utils.cpp
  src/serac/physics/nonlinear_solid.cpp
  src/serac/physics/thermal_conduction.cpp
  src/serac/physics/utilities/equation_solver.cpp
  tests/serac_component_bc.cpp
  tests/serac_input.cpp
Labels: enhancement, input, ready for review

#387 Make the component in coefficients an optional type
  src/serac/infrastructure/input.cpp
  src/serac/infrastructure/input.hpp
  src/serac/physics/elasticity.cpp
  src/serac/physics/elasticity.hpp
  src/serac/physics/nonlinear_solid.cpp
  src/serac/physics/nonlinear_solid.hpp
  src/serac/physics/thermal_solid.hpp
  src/serac/physics/utilities/boundary_condition.cpp
  src/serac/physics/utilities/boundary_condition.hpp
  src/serac/physics/utilities/boundary_condition_manager.cpp
  src/serac/physics/utilities/boundary_condition_manager.hpp
  tests/serac_component_bc.cpp
  tests/serac_error_handling.cpp
  tests/serac_input.cpp
Labels: CS, ready for review, refactoring

#390 Add system zlib to the ubuntu configs
  scripts/spack/configs/linux_ubuntu_20/packages.yaml
Labels: TPL, bug, ready for review

#391 Add thermal conduction to the driver
  data/input_files/default.lua
  src/drivers/serac.cpp
  src/serac/physics/thermal_solid.cpp
  src/serac/physics/thermal_solid.hpp
Labels: input, ready for review

#380 HollowCylinder modifications to do arcs
  src/serac/numerics/mesh_utils.cpp
  src/serac/numerics/mesh_utils.hpp
  tests/mesh_generation.cpp
Labels: discretization, enhancement, ready for review

#356 Add a hook to grab the tangent to the last residual
  src/serac/coefficients/coefficient_extensions.hpp
  src/serac/numerics/mesh_utils.cpp
  src/serac/numerics/mesh_utils.hpp
  src/serac/physics/elasticity.cpp
  src/serac/physics/elasticity.hpp
  src/serac/physics/nonlinear_solid.cpp
  src/serac/physics/nonlinear_solid.hpp
  src/serac/physics/operators/odes.hpp
  tests/serac_nonlinear_solid.cpp
Labels: enhancement, ready for review

#402 Adjust SLIC*_ROOT* macros to automatically retrieve rank
  examples/using-with-cmake/serac_example.cpp
  src/docs/sphinx/dev_guide/logging.rst
  src/drivers/serac.cpp
  src/serac/infrastructure/cli.cpp
  src/serac/infrastructure/cli.hpp
  src/serac/infrastructure/input.cpp
  src/serac/infrastructure/logger.cpp
  src/serac/infrastructure/logger.hpp
  src/serac/numerics/mesh_utils.cpp
  src/serac/physics/base_physics.cpp
  src/serac/physics/elasticity.cpp
  src/serac/physics/nonlinear_solid.cpp
  src/serac/physics/thermal_solid.cpp
  tests/mesh_generation.cpp
  tests/serac_error_handling.cpp
  tests/serac_input.cpp
  tests/serac_newmark_test.cpp
Labels: CS, enhancement

#381 Theory documentation and doxygen clean-up
  .gitignore
  src/docs/doxygen/Doxyfile.in
  src/docs/doxygen/mainpage.md
  src/docs/index.rst
  src/docs/sphinx/dev_guide/docker_dev_env.rst
  src/docs/sphinx/figures/deformed_body.png
  src/docs/sphinx/quickstart.rst
  src/docs/sphinx/theory_reference/index.rst
  src/docs/sphinx/theory_reference/solid.rst
  src/docs/sphinx/theory_reference/thermal.rst
  src/drivers/serac.cpp
  src/serac/coefficients/coefficient_extensions.hpp
  src/serac/infrastructure/input.hpp
  src/serac/infrastructure/terminator.hpp
  src/serac/integrators/wrapper_integrator.hpp
  src/serac/numerics/expr_template_impl.hpp
  src/serac/numerics/mesh_utils.cpp
  src/serac/numerics/mesh_utils.hpp
  src/serac/physics/base_physics.hpp
  src/serac/physics/elasticity.cpp
  src/serac/physics/elasticity.hpp
  src/serac/physics/nonlinear_solid.hpp
  src/serac/physics/operators/odes.hpp
  src/serac/physics/operators/stdfunction_operator.hpp
  src/serac/physics/thermal_conduction.hpp
  src/serac/physics/thermal_solid.hpp
  src/serac/physics/utilities/boundary_condition.hpp
  src/serac/physics/utilities/boundary_condition_manager.hpp
  src/serac/physics/utilities/equation_solver.hpp
  src/serac/physics/utilities/solver_config.hpp
Labels: discretization, documentation, ready for review
