Repository LLNL/serac, pull requests merged in 2021-05, with the labels that each got.

#456 Feature/white238/osxbuild
  .uberenv_config.json
  cmake/thirdparty/SetupSeracThirdParty.cmake
  scripts/spack/configs/darwin/compilers.yaml
  scripts/spack/configs/darwin/packages.yaml
  src/docs/sphinx/quickstart.rst
Labels: CS, TPL, build, ready for review

#458 Add check for mpi compiler wrappers
  CMakeLists.txt
Labels: CS, build, enhancement, good first issue, ready for review

#460 fix and clarify devtools install
  src/docs/sphinx/quickstart.rst
Labels: CS, bug, build, documentation

#461 Update script after switching to submodule for uberenv
  scripts/gitlab/update-uberenv.sh
Labels: CI

#466 Upgrade pip for full quartz builds
  .gitlab/build_quartz.yml
Labels: CI, bug

#467 Task/white238/smith fixes
  .gitlab-ci.yml
  scripts/llnl/build_devtools.py
  scripts/llnl/build_src.py
  scripts/llnl/build_tpls.py
  src/docs/sphinx/quickstart.rst
Labels: CI, CS, TPL, build

#469 Add coefficient accessors to FEState
  src/serac/physics/utilities/finite_element_state.hpp
  tests/serac_thermal_structural_solver.cpp
Labels: enhancement

#471 Harden BLT tools options
  CMakeLists.txt
Labels: CS, bug, build, ready for review

#472 Remove BLT_EXPORT_THIRDPARTY workaround
  CMakeLists.txt
  cmake/thirdparty/SetupSeracThirdParty.cmake
  examples/using-with-cmake/CMakeLists.txt
Labels: CS, build, ready for review

#474 Fix WSL/Ubuntu 20 TPL build
  scripts/spack/configs/linux_ubuntu_20/compilers.yaml
Labels: TPL, ready for review

#418 Feature/variational form
  .gitlab/build_lassen.yml
  cmake/SeracMacros.cmake
  data/meshes/inline-quad.mesh
  data/meshes/toroid-hex.mesh
  host-configs/lassen-blueos_3_ppc64le_ib_p9-clang@10.0.1.cmake
  host-configs/rzansel-blueos_3_ppc64le_ib_p9-clang@10.0.1.cmake
  scripts/spack/configs/blueos_3_ppc64le_ib_p9/packages.yaml
  scripts/spack/packages/serac/package.py
  src/docs/doxygen/mainpage.md
  src/docs/index.rst
  src/docs/sphinx/dev_guide/index.rst
  src/docs/sphinx/dev_guide/tensor_dual.rst
  src/docs/sphinx/dev_guide/weak_form.rst
  src/docs/sphinx/theory_reference/index.rst
  src/docs/sphinx/user_guide/input_schema.rst
  src/serac/infrastructure/accelerator.hpp
  src/serac/numerics/expr_template_impl.hpp
  src/serac/physics/operators/odes.cpp
  src/serac/physics/utilities/CMakeLists.txt
  src/serac/physics/utilities/weak_form/CMakeLists.txt
  src/serac/physics/utilities/weak_form/boundary_integral.hpp
  src/serac/physics/utilities/weak_form/detail/hexahedron_h1.inl
  src/serac/physics/utilities/weak_form/detail/hexahedron_hcurl.inl
  src/serac/physics/utilities/weak_form/detail/metaprogramming.hpp
  src/serac/physics/utilities/weak_form/detail/quadrilateral_L2.inl
  src/serac/physics/utilities/weak_form/detail/quadrilateral_h1.inl
  src/serac/physics/utilities/weak_form/detail/quadrilateral_hcurl.inl
  src/serac/physics/utilities/weak_form/detail/segment_h1.inl
  src/serac/physics/utilities/weak_form/dual.hpp
  src/serac/physics/utilities/weak_form/finite_element.hpp
  src/serac/physics/utilities/weak_form/integral.hpp
  src/serac/physics/utilities/weak_form/polynomials.hpp
  src/serac/physics/utilities/weak_form/quadrature.hpp
  src/serac/physics/utilities/weak_form/tensor.hpp
  src/serac/physics/utilities/weak_form/tests/CMakeLists.txt
  src/serac/physics/utilities/weak_form/tests/hcurl_unit_tests.cpp
  src/serac/physics/utilities/weak_form/tests/l2_comparison.cpp
  src/serac/physics/utilities/weak_form/tests/performance/J2_material_with_AD.cpp
  src/serac/physics/utilities/weak_form/tests/performance/diffusion_performance_test.cpp
  src/serac/physics/utilities/weak_form/tests/performance/kernel_microbenchmark.cpp
  src/serac/physics/utilities/weak_form/tests/tensor_unit_tests.cpp
  src/serac/physics/utilities/weak_form/tests/tensor_unit_tests_cuda.cu
  src/serac/physics/utilities/weak_form/tests/test_tensor_ad.cpp
  src/serac/physics/utilities/weak_form/tests/tuple_arithmetic_unit_tests.cpp
  src/serac/physics/utilities/weak_form/tests/variadic_test_cuda.cu
  src/serac/physics/utilities/weak_form/tests/weak_form_boundary_test.cpp
  src/serac/physics/utilities/weak_form/tests/weak_form_comparisons.cpp
  src/serac/physics/utilities/weak_form/tuple_arithmetic.hpp
  src/serac/physics/utilities/weak_form/weak_form.hpp
Labels: WIP, enhancement, gpu, help wanted

#476 Rename WeakForm to Functional
  src/docs/doxygen/mainpage.md
  src/docs/sphinx/dev_guide/functional.rst
  src/docs/sphinx/dev_guide/index.rst
  src/serac/physics/integrators/traction_integrator.cpp
  src/serac/physics/utilities/CMakeLists.txt
  src/serac/physics/utilities/functional/CMakeLists.txt
  src/serac/physics/utilities/functional/boundary_integral.hpp
  src/serac/physics/utilities/functional/detail/hexahedron_h1.inl
  src/serac/physics/utilities/functional/detail/hexahedron_hcurl.inl
  src/serac/physics/utilities/functional/detail/metaprogramming.hpp
  src/serac/physics/utilities/functional/detail/quadrilateral_L2.inl
  src/serac/physics/utilities/functional/detail/quadrilateral_h1.inl
  src/serac/physics/utilities/functional/detail/quadrilateral_hcurl.inl
  src/serac/physics/utilities/functional/detail/segment_h1.inl
  src/serac/physics/utilities/functional/dual.hpp
  src/serac/physics/utilities/functional/finite_element.hpp
  src/serac/physics/utilities/functional/functional.hpp
  src/serac/physics/utilities/functional/integral.hpp
  src/serac/physics/utilities/functional/polynomials.hpp
  src/serac/physics/utilities/functional/quadrature.hpp
  src/serac/physics/utilities/functional/tensor.hpp
  src/serac/physics/utilities/functional/tests/CMakeLists.txt
  src/serac/physics/utilities/functional/tests/functional_boundary_test.cpp
  src/serac/physics/utilities/functional/tests/functional_comparisons.cpp
  src/serac/physics/utilities/functional/tests/hcurl_unit_tests.cpp
  src/serac/physics/utilities/functional/tests/l2_comparison.cpp
  src/serac/physics/utilities/functional/tests/performance/J2_material_with_AD.cpp
  src/serac/physics/utilities/functional/tests/performance/diffusion_performance_test.cpp
  src/serac/physics/utilities/functional/tests/performance/kernel_microbenchmark.cpp
  src/serac/physics/utilities/functional/tests/tensor_unit_tests.cpp
  src/serac/physics/utilities/functional/tests/tensor_unit_tests_cuda.cu
  src/serac/physics/utilities/functional/tests/test_tensor_ad.cpp
  src/serac/physics/utilities/functional/tests/tuple_arithmetic_unit_tests.cpp
  src/serac/physics/utilities/functional/tests/variadic_test_cuda.cu
  src/serac/physics/utilities/functional/tuple_arithmetic.hpp
Labels: ready for review, refactoring
