Repository LLNL/serac, pull requests merged in 2021-12, with the labels that each got.

#607 Fix Simple Conduction example and clarify couple small things
  examples/simple_conduction/CMakeLists.txt
  examples/simple_conduction/conduction.lua
  src/docs/sphinx/user_guide/input_schema.rst
  src/serac/mesh/mesh_utils.cpp
  src/serac/mesh/tests/mesh_generation.cpp
Labels: bug, ready for review, input

#608 Add development warning to docs
  README.md
  src/docs/index.rst
Labels: documentation

#609 Fix the indentation problem
  src/docs/index.rst
Labels: documentation

#610 Get rid of Sidre warnings from `BasePhysics::saveSummary()`
  src/serac/physics/base_physics.cpp
Labels: bug, CS, ready for review, output

#612 Fix the default BC in the adjoint solid solve
  src/serac/physics/solid.cpp
  src/serac/physics/tests/serac_solid_adjoint.cpp
Labels: bug, discretization, ready for review

#613 Fix the MFEM/Axom co-develop documentation
  cmake/thirdparty/SetupSeracThirdParty.cmake
  src/docs/sphinx/dev_guide/mfem_dev.rst
Labels: documentation, ready for review

#615 Fix the solid sensitivity calculations
  src/serac/physics/coefficients/sensitivity_coefficients.cpp
  src/serac/physics/coefficients/sensitivity_coefficients.hpp
  src/serac/physics/solid.cpp
  src/serac/physics/tests/CMakeLists.txt
  src/serac/physics/tests/serac_solid_adjoint.cpp
  src/serac/physics/tests/serac_solid_sensitivity.cpp
Labels: bug, discretization, ready for review

#616 Remove Ascent
  cmake/SeracConfigHeader.cmake
  cmake/serac-config.cmake.in
  cmake/thirdparty/SetupSeracThirdParty.cmake
  host-configs/docker/docker-linux-ubuntu20.04-ivybridge-clang@10.0.0.cmake
  host-configs/docker/docker-linux-ubuntu20.04-ivybridge-gcc@9.3.0.cmake
  host-configs/lassen-blueos_3_ppc64le_ib_p9-clang@10.0.1.cmake
  host-configs/quartz-toss_3_x86_64_ib-clang@10.0.0.cmake
  host-configs/quartz-toss_3_x86_64_ib-gcc@8.3.1.cmake
  host-configs/rzansel-blueos_3_ppc64le_ib_p9-clang@10.0.1.cmake
  host-configs/rzgenie-toss_3_x86_64_ib-clang@10.0.0.cmake
  host-configs/rzgenie-toss_3_x86_64_ib-gcc@8.3.1.cmake
  scripts/spack/packages/ascent/package.py
  scripts/spack/packages/serac/package.py
  src/docs/sphinx/user_guide/command_line_options.rst
  src/drivers/serac.cpp
  src/serac/infrastructure/CMakeLists.txt
  src/serac/infrastructure/cli.cpp
  src/serac/infrastructure/output.cpp
  src/serac/infrastructure/output.hpp
  src/serac/serac_config.hpp.in
Labels: TPL
