Repository LLNL/serac, pull requests merged in 2021-03, with the labels that each got.

#405 Clean up the doc styles
  src/docs/_static/theme_overrides.css
  src/docs/conf.py
  src/docs/sphinx/dev_guide/docker_env.rst
  src/docs/sphinx/dev_guide/expr_templates.rst
  src/docs/sphinx/dev_guide/index.rst
  src/docs/sphinx/quickstart.rst
  src/docs/sphinx/user_guide/index.rst
  src/docs/sphinx/user_guide/input_schema.rst
Labels: documentation, ready for review

#404 Move the SLIC calls back to ROOT
  src/serac/infrastructure/accelerator.cpp
  src/serac/infrastructure/input.cpp
  src/serac/infrastructure/profiling.cpp
  src/serac/numerics/mesh_utils.cpp
  src/serac/physics/nonlinear_solid.cpp
  src/serac/physics/operators/odes.cpp
  src/serac/physics/thermal_conduction.cpp
  src/serac/physics/utilities/boundary_condition.cpp
  src/serac/physics/utilities/boundary_condition.hpp
  src/serac/physics/utilities/boundary_condition_manager.cpp
  src/serac/physics/utilities/equation_solver.cpp
Labels: CS, ready for review

#373 Add a nonlinear reaction option to the thermal module
  data/input_files/tests/thermal_conduction/static_reaction_exact.lua
  data/input_files/tests/thermal_conduction/static_solve.lua
  src/serac/physics/base_physics.cpp
  src/serac/physics/base_physics.hpp
  src/serac/physics/integrators/CMakeLists.txt
  src/serac/physics/integrators/nonlinear_reaction_integrator.cpp
  src/serac/physics/integrators/nonlinear_reaction_integrator.hpp
  src/serac/physics/integrators/wrapper_integrator.cpp
  src/serac/physics/integrators/wrapper_integrator.hpp
  src/serac/physics/solid.cpp
  src/serac/physics/thermal_conduction.cpp
  src/serac/physics/thermal_conduction.hpp
  tests/serac_wrapper_tests.cpp
Labels: discretization, enhancement, ready for review

#407 Fix the doxygen mainpage to include the new solid module
  src/docs/doxygen/mainpage.md
  src/serac/infrastructure/cli.hpp
Labels: bug, documentation, ready for review

#410 Small documentation fixes
  src/docs/sphinx/user_guide/index.rst
  src/serac/physics/integrators/nonlinear_reaction_integrator.cpp
  src/serac/physics/integrators/nonlinear_reaction_integrator.hpp
  src/serac/physics/thermal_conduction.cpp
Labels: bug, documentation

#409 Enable reuse of a mesh with two solid modules
  src/serac/physics/integrators/displacement_hyperelastic_integrator.cpp
  src/serac/physics/integrators/displacement_hyperelastic_integrator.hpp
  src/serac/physics/solid.cpp
  src/serac/physics/solid.hpp
  src/serac/physics/utilities/solver_config.hpp
  tests/CMakeLists.txt
  tests/serac_solid_reuse_mesh.cpp
Labels: bug, discretization, ready for review

#398 Refactor mesh utilities to reduce dependence on Inlet
  data/input_files/tests/meshing/meshing.lua
  src/drivers/serac.cpp
  src/serac/numerics/mesh_utils.cpp
  src/serac/numerics/mesh_utils.hpp
  tests/mesh_generation.cpp
  tests/serac_component_bc.cpp
  tests/serac_dtor.cpp
  tests/serac_mesh.cpp
  tests/serac_newmark_test.cpp
  tests/serac_solid.cpp
  tests/serac_solid_reuse_mesh.cpp
  tests/serac_thermal_structural_solver.cpp
  tests/test_utilities.cpp
Labels: ready for review, refactoring

#411 Return meshes by value, expose disk + ball meshes from Inlet
  data/input_files/tests/meshing/meshing.lua
  data/input_files/tests/solid/dyn_newmark_solve.lua
  data/input_files/tests/solid/dyn_newmark_solve_bending.lua
  data/input_files/tests/solid/dyn_newmark_solve_bending_first.lua
  data/input_files/tests/thermal_conduction/static_amgx_solve.lua
  data/input_files/tests/thermal_conduction/static_solve.lua
  src/serac/numerics/mesh_utils.cpp
  src/serac/numerics/mesh_utils.hpp
  tests/mesh_generation.cpp
  tests/serac_dtor.cpp
  tests/serac_error_handling.cpp
  tests/serac_mesh.cpp
  tests/serac_newmark_test.cpp
  tests/serac_solid_reuse_mesh.cpp
  tests/serac_thermal_solver.cpp
  tests/serac_thermal_structural_solver.cpp
  tests/test_utilities.cpp
  tests/test_utilities.hpp
Labels: enhancement, ready for review

#421 Add an option to allocate the gridfunction outside of sidre
  src/serac/physics/utilities/finite_element_state.cpp
  src/serac/physics/utilities/finite_element_state.hpp
  tests/serac_error_handling.cpp
Labels: CS, bug, ready for review

#414 Switch to conduit for AMGX configuration
  src/serac/physics/utilities/equation_solver.cpp
Labels: CS, ready for review, refactoring

#422 Update docs to new path
  src/docs/sphinx/quickstart.rst
Labels: TPL, bug, build, documentation, ready for review

#426 FIX: CI quartz skip and resource release
  .gitlab/build_quartz.yml
Labels: CI, ready for review

#377 Adding extra caliper markers and metadata methods
  src/docs/sphinx/dev_guide/profiling.rst
  src/serac/infrastructure/profiling.cpp
  src/serac/infrastructure/profiling.hpp
  src/serac/physics/integrators/displacement_hyperelastic_integrator.cpp
  src/serac/physics/utilities/equation_solver.cpp
  tests/CMakeLists.txt
  tests/serac_profiling.cpp
Labels: CS, ready for review

#427 Add new SLIC streams that write to single file
  src/serac/infrastructure/logger.cpp
Labels: CS, ready for review

#431 Banish Puke Green
  src/docs/conf.py
Labels: documentation, enhancement, ready for review
