Repository LLNL/serac, pull requests merged in 2021-04, with the labels that each got.

#438 Fix full build rule
  .gitlab-ci.yml
  .gitlab/build_lassen.yml
  .gitlab/build_quartz.yml
Labels: CI, bug

#444 merged PR from forks from Geoffrey
  CMakeLists.txt
  scripts/spack/packages/serac/package.py
Labels: CS, bug, build, ready for review

#434 Add option to select language/sidre path for Inlet
  src/serac/infrastructure/input.cpp
  src/serac/infrastructure/input.hpp
Labels: CS, ready for review, refactoring

#450 Update to new Spack CachedCMakePackage
  .gitlab/build_lassen.yml
  .uberenv_config.json
  azure-pipelines.yml
  host-configs/docker/docker-linux-ubuntu16.04-x86_64-gcc@8.1.0.cmake
  host-configs/docker/docker-linux-ubuntu18.04-x86_64-clang@10.0.0.cmake
  host-configs/lassen-blueos_3_ppc64le_ib_p9-clang@10.0.1-cuda.cmake
  host-configs/lassen-blueos_3_ppc64le_ib_p9-clang@10.0.1.cmake
  host-configs/quartz-toss_3_x86_64_ib-clang@10.0.0.cmake
  host-configs/quartz-toss_3_x86_64_ib-gcc@8.3.1.cmake
  host-configs/rzansel-blueos_3_ppc64le_ib_p9-clang@10.0.1-cuda.cmake
  host-configs/rzansel-blueos_3_ppc64le_ib_p9-clang@10.0.1.cmake
  host-configs/rzgenie-toss_3_x86_64_ib-clang@10.0.0.cmake
  host-configs/rzgenie-toss_3_x86_64_ib-gcc@8.3.1.cmake
  scripts/spack/packages/axom/package.py
  scripts/spack/packages/serac/package.py
Labels: CS, TPL, build

#452 Add the name parameter to the inlet-specified physics module
  src/serac/physics/solid.cpp
  src/serac/physics/solid.hpp
  src/serac/physics/thermal_conduction.cpp
  src/serac/physics/thermal_conduction.hpp
  src/serac/physics/thermal_solid.cpp
  src/serac/physics/thermal_solid.hpp
  tests/serac_thermal_structural_solver.cpp
Labels: bug, ready for review

#455 Rectangular StdFunctionOperators
  src/serac/physics/operators/stdfunction_operator.hpp
  tests/CMakeLists.txt
  tests/serac_operator.cpp
Labels: enhancement, ready for review

#448 WIP: Doxygen documentation/misc cleanup of variational form
  host-configs/lassen-blueos_3_ppc64le_ib_p9-clang@10.0.1-cuda.cmake
  src/docs/doxygen/mainpage.md
  src/serac/physics/utilities/variational_form/CMakeLists.txt
  src/serac/physics/utilities/variational_form/array.hpp
  src/serac/physics/utilities/variational_form/detail/hexahedron_hcurl.inl
  src/serac/physics/utilities/variational_form/detail/meta.h
  src/serac/physics/utilities/variational_form/dual.hpp
  src/serac/physics/utilities/variational_form/finite_element.hpp
  src/serac/physics/utilities/variational_form/integral.hpp
  src/serac/physics/utilities/variational_form/polynomials.hpp
  src/serac/physics/utilities/variational_form/quadrature.hpp
  src/serac/physics/utilities/variational_form/tensor.hpp
  src/serac/physics/utilities/variational_form/tests/J2_material_with_AD.cpp
  src/serac/physics/utilities/variational_form/tests/diffusion_performance_test.cpp
  src/serac/physics/utilities/variational_form/tests/hcurl_unit_tests.cpp
  src/serac/physics/utilities/variational_form/tests/l2_comparison.cpp
  src/serac/physics/utilities/variational_form/tests/tensor_unit_tests.cpp
  src/serac/physics/utilities/variational_form/tests/test_tensor_ad.cpp
  src/serac/physics/utilities/variational_form/tests/tuple_arithmetic_unit_tests.cpp
  src/serac/physics/utilities/variational_form/tests/weak_form_boundary_test.cpp
  src/serac/physics/utilities/variational_form/tuple_arithmetic.hpp
  src/serac/physics/utilities/variational_form/weak_form.hpp
Labels: documentation
