Repository LLNL/serac, pull requests merged in 2021-09, with the labels that each got.

#554 Add a dual type for linear forms
  src/serac/physics/solid.cpp
  src/serac/physics/solid.hpp
  src/serac/physics/tests/serac_solid_adjoint.cpp
  src/serac/physics/utilities/CMakeLists.txt
  src/serac/physics/utilities/finite_element_dual.hpp
  src/serac/physics/utilities/finite_element_state.cpp
  src/serac/physics/utilities/finite_element_state.hpp
  src/serac/physics/utilities/finite_element_vector.cpp
  src/serac/physics/utilities/finite_element_vector.hpp
  src/serac/physics/utilities/state_manager.cpp
  src/serac/physics/utilities/state_manager.hpp
Labels: discretization, ready for review

#556 Add doxygen/sphinx warnings CI check
  azure-pipelines.yml
  scripts/azure-pipelines/docs_ignore_regexs.txt
  scripts/azure-pipelines/linux-check.sh
  scripts/check_log.py
  scripts/docker/dockerfile.in
  scripts/docker/dockerfile_clang-10
  scripts/docker/dockerfile_gcc-8
  scripts/docker/dockerfile_gcc-9
  scripts/spack/configs/docker/ubuntu20/packages.yaml
Labels: documentation, CI, testing

#563 Fix the doxygen warnings and turn on the CI check
  scripts/azure-pipelines/docs_ignore_regexs.txt
  scripts/check_log.py
  src/serac/infrastructure/accelerator.hpp
  src/serac/physics/utilities/finite_element_vector.hpp
  src/serac/physics/utilities/functional/boundary_integral.hpp
  src/serac/physics/utilities/functional/domain_integral.hpp
  src/serac/physics/utilities/functional/finite_element.hpp
  src/serac/physics/utilities/functional/functional.hpp
  src/serac/physics/utilities/functional/integral_utilities.hpp
  src/serac/physics/utilities/functional/tensor.hpp
  src/serac/physics/utilities/functional/tuple.hpp
Labels: documentation, ready for review, CI
