Repository LLNL/serac, pull requests merged in 2021-11, with the labels that each got.

#589 Fix the dual space transfer operators
  src/serac/physics/state/finite_element_dual.hpp
  src/serac/physics/state/finite_element_state.hpp
  src/serac/physics/state/finite_element_vector.cpp
  src/serac/physics/state/finite_element_vector.hpp
Labels: bug, discretization, ready for review

#594 Add missing files to the header installs
  src/serac/numerics/functional/CMakeLists.txt
Labels: bug, ready for review

#598 Cleanup summary file checker
  examples/using-with-cmake/CMakeLists.txt
  host-configs/devbuild.cmake
  scripts/testing/tolerance_test.py
  src/serac/physics/base_physics.cpp
Labels: ready for review, testing

#604 Fix example build issues
  examples/host-config.cmake.in
  examples/using-with-cmake/CMakeLists.txt
Labels: bug, ready for review

#590 Add a functional-enabled version of thermal conduction
  src/serac/numerics/functional/boundary_integral.hpp
  src/serac/numerics/functional/domain_integral.hpp
  src/serac/numerics/functional/functional.hpp
  src/serac/numerics/functional/tensor.hpp
  src/serac/physics/CMakeLists.txt
  src/serac/physics/base_physics.cpp
  src/serac/physics/materials/CMakeLists.txt
  src/serac/physics/materials/thermal_functional_material.hpp
  src/serac/physics/tests/CMakeLists.txt
  src/serac/physics/tests/serac_thermal_functional.cpp
  src/serac/physics/thermal_conduction_functional.hpp
Labels: discretization, ready for review
