Repository LLNL/serac, pull requests merged in 2022-08, with the labels that each got.

#757 Use SuperLU for the static solid functional tests
  src/serac/physics/tests/serac_solid_functional.cpp
Labels: ready for review, CI

#759 cleanup mailmap
  .mailmap
Labels: CS, ready for review

#766 Remove debug printing
  cmake/thirdparty/SetupSeracThirdParty.cmake
Labels: bug, build, TPL

#768 Improve codevelop for Smith
  cmake/thirdparty/SetupSeracThirdParty.cmake
Labels: build, TPL

#772 Use non-relative path to find serac
  CMakeLists.txt
  cmake/thirdparty/SetupSeracThirdParty.cmake
Labels: bug, CS, build, TPL

#763 Clean up the direct solver option
  src/serac/numerics/equation_solver.cpp
  src/serac/numerics/equation_solver.hpp
  src/serac/physics/solid_functional.hpp
  src/serac/physics/tests/serac_solid_functional.cpp
Labels: discretization, ready for review

#778 Turn on SLIC Root filtering functionality
  src/serac/infrastructure/logger.cpp
Labels: bug, CS, output
