Repository LLNL/serac, pull requests merged in 2022-04, with the labels that each got.

#658 Add parameterizations and sensitivities to `SolidFunctional`
  src/serac/physics/materials/CMakeLists.txt
  src/serac/physics/materials/functional_material_utils.hpp
  src/serac/physics/materials/parameterized_solid_functional_material.hpp
  src/serac/physics/materials/solid_functional_material.hpp
  src/serac/physics/solid_functional.hpp
  src/serac/physics/tests/CMakeLists.txt
  src/serac/physics/tests/serac_solid_functional.cpp
  src/serac/physics/tests/serac_solid_functional_finite_diff.cpp
  src/serac/physics/thermal_conduction_functional.hpp
Labels: discretization, ready for review

#675 Use correct CMake MPI variables for Adiak
  scripts/spack/packages/adiak/package.py
Labels: TPL

#676 Fix a downstream cmake build
  cmake/serac-config.cmake.in
  scripts/gitlab/build_and_test.sh
Labels: ready for review, build

#680 Minor issue found while looking at code
  src/serac/infrastructure/input.cpp
  src/serac/infrastructure/input.hpp
Labels: documentation, CS

#685 Check error status of commands run in gitlab script
  scripts/gitlab/build_and_test.sh
Labels: bug, CS, CI

#681 Feature/talamini/thermal solid functional
  src/serac/physics/CMakeLists.txt
  src/serac/physics/materials/CMakeLists.txt
  src/serac/physics/materials/tests/CMakeLists.txt
  src/serac/physics/materials/tests/thermomechanical_material.cpp
  src/serac/physics/tests/CMakeLists.txt
  src/serac/physics/tests/serac_thermal_solid_functional.cpp
  src/serac/physics/thermal_solid_functional.hpp
Labels: discretization, ready for review
