Repository LLNL/serac, pull requests merged in 2022-07, with the labels that each got.

#743 Increase the wait for summary files in testing
  scripts/testing/tolerance_test.py
Labels: ready for review, CI

#739 Clean up the boundary condition projection methods
  data/input_files/tests/solid/dyn_newmark_solve_bending_first.lua
  src/serac/infrastructure/tests/serac_error_handling.cpp
  src/serac/numerics/odes.cpp
  src/serac/numerics/tests/serac_odes.cpp
  src/serac/physics/base_physics.cpp
  src/serac/physics/boundary_conditions/boundary_condition.cpp
  src/serac/physics/boundary_conditions/boundary_condition.hpp
  src/serac/physics/boundary_conditions/boundary_condition_manager.cpp
  src/serac/physics/boundary_conditions/boundary_condition_manager.hpp
  src/serac/physics/boundary_conditions/tests/serac_boundary_cond.cpp
  src/serac/physics/solid.cpp
  src/serac/physics/solid_functional.hpp
  src/serac/physics/state/finite_element_vector.hpp
  src/serac/physics/tests/serac_newmark_test.cpp
  src/serac/physics/thermal_conduction.cpp
  src/serac/physics/thermal_conduction_functional.hpp
Labels: discretization

#749 fix devtools paths
  host-configs/rzansel-blueos_3_ppc64le_ib_p9-clang@10.0.1.cmake
  scripts/spack/devtools_configs/blueos_3_ppc64le_ib_p9/packages.yaml
Labels: CS, build, TPL

#744 Enabling codevelop in Smith
  cmake/thirdparty/SetupSeracThirdParty.cmake
Labels: WIP, build

#753 Fix boundary condition bug
  src/serac/physics/boundary_conditions/boundary_condition.cpp
  src/serac/physics/tests/CMakeLists.txt
  src/serac/physics/tests/serac_solid_functional_boundary.cpp
Labels: discretization, ready for review
