Repository LLNL/serac, pull requests merged in 2022-03, with the labels that each got.

#640 renamed field to be more understandable
  data/input_files/tests/solid/dyn_amgx_solve.lua
  data/input_files/tests/solid/dyn_direct_solve.lua
  data/input_files/tests/solid/dyn_linesearch_solve.lua
  data/input_files/tests/solid/dyn_newmark_solve.lua
  data/input_files/tests/solid/dyn_newmark_solve_bending.lua
  data/input_files/tests/solid/dyn_newmark_solve_bending_first.lua
  data/input_files/tests/solid/dyn_solve.lua
  data/input_files/tests/solid/qs_attribute_solve.lua
  data/input_files/tests/solid/qs_component_solve.lua
  data/input_files/tests/solid/qs_direct_solve.lua
  data/input_files/tests/solid/qs_linear.lua
  data/input_files/tests/solid/qs_solve.lua
  data/input_files/tests/thermal_conduction/dyn_exp_solve.lua
  data/input_files/tests/thermal_conduction/dyn_imp_solve.lua
  data/input_files/tests/thermal_conduction/dyn_imp_solve_restart.lua
  data/input_files/tests/thermal_conduction/static_amgx_solve.lua
  data/input_files/tests/thermal_conduction/static_solve.lua
  data/input_files/tests/thermal_conduction/static_solve_multiple_bcs.lua
  data/input_files/tests/thermal_conduction/static_solve_repeated_bcs.lua
  data/input_files/tests/thermal_solid/thermal_expansion.lua
  src/serac/physics/coefficients/tests/serac_component_bc.cpp
  src/serac/physics/tests/serac_solid.cpp
  src/serac/physics/tests/test_utilities.cpp
Labels: ready for review, input

#642 Add missing <optional> header
  src/serac/infrastructure/input.hpp
Labels: CS, ready for review, build

#638 Thermal sensitivities with `Functional`
  src/serac/infrastructure/about.cpp
  src/serac/infrastructure/input.cpp
  src/serac/numerics/functional/boundary_integral.hpp
  src/serac/numerics/functional/boundary_integral_kernels.hpp
  src/serac/numerics/functional/domain_integral.hpp
  src/serac/numerics/functional/domain_integral_kernels.hpp
  src/serac/numerics/functional/dual.hpp
  src/serac/numerics/functional/evector_view.hpp
  src/serac/numerics/functional/functional.hpp
  src/serac/numerics/functional/functional_qoi.inl
  src/serac/numerics/functional/quadrature.hpp
  src/serac/numerics/functional/tensor.hpp
  src/serac/numerics/functional/tests/tuple_arithmetic_unit_tests.cpp
  src/serac/numerics/functional/tuple.hpp
  src/serac/physics/materials/CMakeLists.txt
  src/serac/physics/materials/functional_material_utils.hpp
  src/serac/physics/materials/parameterized_thermal_functional_material.hpp
  src/serac/physics/materials/thermal_functional_material.hpp
  src/serac/physics/solid.hpp
  src/serac/physics/state/finite_element_vector.cpp
  src/serac/physics/state/finite_element_vector.hpp
  src/serac/physics/tests/CMakeLists.txt
  src/serac/physics/tests/serac_thermal_functional.cpp
  src/serac/physics/tests/serac_thermal_functional_finite_diff.cpp
  src/serac/physics/thermal_conduction_functional.hpp
Labels: discretization, ready for review

#626 Performance tracking with Adiak/Caliper/Spot
  .gitignore
  cmake/SeracBasics.cmake
  cmake/SeracConfigHeader.cmake
  cmake/serac-config.cmake.in
  cmake/thirdparty/SetupSeracThirdParty.cmake
  scripts/azure-pipelines/docs_ignore_regexs.txt
  scripts/spack/packages/serac/package.py
  src/docs/sphinx/dev_guide/profiling.rst
  src/serac/infrastructure/CMakeLists.txt
  src/serac/infrastructure/initialize.cpp
  src/serac/infrastructure/profiling.cpp
  src/serac/infrastructure/profiling.hpp
  src/serac/infrastructure/terminator.cpp
  src/serac/infrastructure/tests/CMakeLists.txt
  src/serac/infrastructure/tests/serac_profiling.cpp
  src/serac/mesh/tests/CMakeLists.txt
  src/serac/numerics/functional/CMakeLists.txt
  src/serac/numerics/functional/domain_integral.hpp
  src/serac/numerics/functional/tests/functional_comparisons.cpp
  src/serac/numerics/functional/tests/functional_comparisons_cuda.cu
  src/serac/numerics/functional/tests/functional_nonlinear.cpp
  src/serac/numerics/tests/CMakeLists.txt
  src/serac/physics/CMakeLists.txt
  src/serac/physics/benchmarks/CMakeLists.txt
  src/serac/physics/benchmarks/benchmark_serac_thermal_functional.cpp
  src/serac/physics/boundary_conditions/tests/CMakeLists.txt
  src/serac/physics/coefficients/tests/CMakeLists.txt
  src/serac/physics/integrators/displacement_hyperelastic_integrator.cpp
  src/serac/physics/integrators/tests/CMakeLists.txt
  src/serac/physics/tests/CMakeLists.txt
  src/serac/serac_config.hpp.in
Labels: CS, ready for review
