Repository LLNL/serac, pull requests merged in 2022-12, with the labels that each got.

#840 Add shape sensitivity to the thermal module
  src/serac/numerics/functional/tensor.hpp
  src/serac/numerics/odes.cpp
  src/serac/numerics/odes.hpp
  src/serac/numerics/tests/odes.cpp
  src/serac/physics/base_physics.cpp
  src/serac/physics/boundary_conditions/boundary_condition.cpp
  src/serac/physics/heat_transfer.hpp
  src/serac/physics/materials/green_saint_venant_thermoelastic.hpp
  src/serac/physics/materials/parameterized_thermal_material.hpp
  src/serac/physics/materials/thermal_material.hpp
  src/serac/physics/solid_legacy.cpp
  src/serac/physics/state/finite_element_state.cpp
  src/serac/physics/state/finite_element_state.hpp
  src/serac/physics/state/finite_element_vector.cpp
  src/serac/physics/state/finite_element_vector.hpp
  src/serac/physics/state/state_manager.cpp
  src/serac/physics/state/state_manager.hpp
  src/serac/physics/tests/CMakeLists.txt
  src/serac/physics/tests/parameterized_thermal.cpp
  src/serac/physics/tests/parameterized_thermomechanics_example.cpp
  src/serac/physics/tests/solid_finite_diff.cpp
  src/serac/physics/tests/solid_legacy_adjoint.cpp
  src/serac/physics/tests/solid_legacy_sensitivity.cpp
  src/serac/physics/tests/thermal.cpp
  src/serac/physics/tests/thermal_dynamics_patch.cpp
  src/serac/physics/tests/thermal_finite_diff.cpp
  src/serac/physics/tests/thermal_mechanics.cpp
  src/serac/physics/tests/thermal_shape.cpp
  src/serac/physics/tests/thermal_statics_patch.cpp
  src/serac/physics/thermal_conduction_legacy.cpp
  src/serac/physics/thermomechanics.hpp
Labels: discretization, ready for review

#861 Add SERAC_USE_CAMP cmake variable
  cmake/SeracConfigHeader.cmake
  cmake/serac-config.cmake.in
  cmake/thirdparty/SetupSeracThirdParty.cmake
  src/serac/infrastructure/about.cpp
  src/serac/serac_config.hpp.in
Labels: build

#860 WIP: Reorganizing tests
  src/serac/infrastructure/tests/CMakeLists.txt
  src/serac/infrastructure/tests/error_handling.cpp
  src/serac/infrastructure/tests/profiling.cpp
Labels: refactoring, build, testing

#863 Feature/talamini/nonlinear hardening
  src/serac/numerics/functional/dual.hpp
  src/serac/numerics/functional/tests/test_newton.cpp
  src/serac/numerics/functional/tuple_tensor_dual_functions.hpp
  src/serac/physics/materials/material_verification_tools.hpp
  src/serac/physics/materials/parameterized_solid_material.hpp
  src/serac/physics/materials/solid_material.hpp
  src/serac/physics/materials/tests/CMakeLists.txt
  src/serac/physics/materials/tests/nonlinear_J2_material.cpp
  src/serac/physics/materials/tests/parameterized_nonlinear_J2_material.cpp
Labels: enhancement, ready for review

#865 Fix the `generateParFiniteElementSpace` memory leak
  src/serac/numerics/functional/functional.hpp
  src/serac/numerics/functional/tests/functional_basic_h1_vector.cpp
  src/serac/physics/base_physics.hpp
  src/serac/physics/heat_transfer.hpp
  src/serac/physics/solid_mechanics.hpp
Labels: bug, CS

#868 Make all `FiniteElementState`s use `mfem::Ordering::byNODES`
  src/serac/numerics/equation_solver.cpp
  src/serac/numerics/functional/functional.hpp
  src/serac/physics/solid_legacy.cpp
  src/serac/physics/state/finite_element_vector.cpp
  src/serac/physics/state/finite_element_vector.hpp
  src/serac/physics/state/state_manager.cpp
  src/serac/physics/tests/solid_finite_diff.cpp
  src/serac/physics/tests/solid_legacy_sensitivity.cpp
  src/serac/physics/tests/solid_shape.cpp
  src/serac/physics/thermal_conduction_legacy.cpp
Labels: discretization, ready for review, refactoring
