Repository LLNL/serac, pull requests merged in 2022-01, with the labels that each got.

#617 Bugfix: fix summary file name and remove now unneeded collection name from `StateManager`
  src/drivers/serac.cpp
  src/serac/infrastructure/output.cpp
  src/serac/infrastructure/output.hpp
  src/serac/physics/state/state_manager.cpp
  src/serac/physics/state/state_manager.hpp
Labels: bug, CS

#618 Rzgenie TPL rebuild
  host-configs/rzgenie-toss_3_x86_64_ib-clang@10.0.0.cmake
  host-configs/rzgenie-toss_3_x86_64_ib-gcc@8.3.1.cmake
Labels: TPL

#619 move `tests` under `src`
  CMakeLists.txt
  src/CMakeLists.txt
  src/tests/CMakeLists.txt
  src/tests/axom_smoketest.cpp
  src/tests/copy_elision.cpp
  src/tests/mfem_array_std_algo.cpp
  src/tests/mfem_ex9p_blockilu.cpp
  src/tests/petsc_smoketest.cpp
  src/tests/serac_cuda_smoketest.cpp
  src/tests/serac_cuda_smoketest_kernel.cpp
Labels: CS, ready for review, testing

#620 Fix GCC dereference warning
  azure-pipelines.yml
  src/serac/numerics/quadrature_data.hpp
  src/serac/physics/integrators/wrapper_integrator.cpp
Labels: bug, ready for review, build

#623 Change the example output directory
  examples/simple_conduction/with_input_file.cpp
  examples/simple_conduction/without_input_file.cpp
Labels: bug, ready for review

#625 Codevelop CI testing
  CMakeLists.txt
  README.md
  azure-pipelines.yml
  cmake/serac-config.cmake.in
  examples/using-with-cmake/CMakeLists.txt
  src/docs/sphinx/quickstart.rst
Labels: CS, ready for review, CI, build, TPL, testing

#628 update devtool packages
  scripts/spack/configs/blueos_3_ppc64le_ib_p9/packages.yaml
  scripts/spack/configs/toss_3_x86_64_ib/packages.yaml
Labels: bug, ready for review, TPL
