Repository LLNL/serac, pull requests merged in 2022-06, with the labels that each got.

#714 Fix the boundary condition essential dof list applications
  src/serac/infrastructure/tests/serac_error_handling.cpp
  src/serac/physics/base_physics.cpp
  src/serac/physics/base_physics.hpp
  src/serac/physics/boundary_conditions/boundary_condition.cpp
  src/serac/physics/boundary_conditions/boundary_condition.hpp
  src/serac/physics/boundary_conditions/boundary_condition_manager.cpp
  src/serac/physics/boundary_conditions/boundary_condition_manager.hpp
  src/serac/physics/boundary_conditions/tests/serac_boundary_cond.cpp
Labels: bug, discretization

#715 GTest names
  src/serac/infrastructure/tests/serac_error_handling.cpp
  src/serac/infrastructure/tests/serac_input.cpp
  src/serac/infrastructure/tests/serac_profiling.cpp
  src/serac/mesh/tests/mesh_generation.cpp
  src/serac/mesh/tests/serac_mesh_test.cpp
  src/serac/numerics/functional/tests/CMakeLists.txt
  src/serac/numerics/functional/tests/functional_basic.cpp
  src/serac/numerics/functional/tests/functional_boundary_test.cpp
  src/serac/numerics/functional/tests/functional_comparison_L2.cpp
  src/serac/numerics/functional/tests/functional_comparisons.cpp
  src/serac/numerics/functional/tests/functional_comparisons_cuda.cu
  src/serac/numerics/functional/tests/functional_material_state_test.cpp
  src/serac/numerics/functional/tests/functional_multiphysics.cpp
  src/serac/numerics/functional/tests/functional_nonlinear.cpp
  src/serac/numerics/functional/tests/functional_qoi.cpp
  src/serac/numerics/functional/tests/get_qf_derivative_type.cpp
  src/serac/numerics/functional/tests/hcurl_unit_tests.cpp
  src/serac/numerics/functional/tests/performance/diffusion_performance_test.cpp
  src/serac/numerics/functional/tests/performance/kernel_microbenchmark.cpp
  src/serac/numerics/functional/tests/quadrature_data_cuda.cu
  src/serac/numerics/functional/tests/tensor_unit_tests.cpp
  src/serac/numerics/functional/tests/tensor_unit_tests_cuda.cu
  src/serac/numerics/functional/tests/test_tensor_ad.cpp
  src/serac/numerics/functional/tests/tuple_arithmetic_unit_tests.cpp
  src/serac/numerics/tests/benchmark_expr_templates.cpp
  src/serac/numerics/tests/expr_templates.cpp
  src/serac/numerics/tests/serac_odes.cpp
  src/serac/numerics/tests/serac_operator.cpp
  src/serac/physics/benchmarks/benchmark_serac_thermal_functional.cpp
  src/serac/physics/boundary_conditions/boundary_condition.cpp
  src/serac/physics/boundary_conditions/tests/serac_boundary_cond.cpp
  src/serac/physics/coefficients/tests/serac_component_bc.cpp
  src/serac/physics/integrators/tests/serac_wrapper_tests.cpp
  src/serac/physics/tests/serac_dtor.cpp
  src/serac/physics/tests/serac_newmark_test.cpp
  src/serac/physics/tests/serac_solid.cpp
  src/serac/physics/tests/serac_solid_adjoint.cpp
  src/serac/physics/tests/serac_solid_functional.cpp
  src/serac/physics/tests/serac_solid_functional_finite_diff.cpp
  src/serac/physics/tests/serac_solid_reuse_mesh.cpp
  src/serac/physics/tests/serac_solid_sensitivity.cpp
  src/serac/physics/tests/serac_thermal_expansion.cpp
  src/serac/physics/tests/serac_thermal_functional.cpp
  src/serac/physics/tests/serac_thermal_functional_finite_diff.cpp
  src/serac/physics/tests/serac_thermal_solid_functional.cpp
  src/serac/physics/tests/serac_thermal_solid_solver.cpp
  src/serac/physics/tests/serac_thermal_solver.cpp
  src/serac/physics/tests/serac_thermal_structural_solver.cpp
  src/serac/physics/tests/test_utilities.cpp
  src/serac/physics/tests/test_utilities.hpp
  src/tests/copy_elision.cpp
  src/tests/mfem_array_std_algo.cpp
  src/tests/petsc_smoketest.cpp
  src/tests/serac_cuda_smoketest.cpp
Labels: CS, testing

#719 Added error check in ats
  scripts/testing/ats.sh.in
Labels: ready for review

#720 Clean up some easy Cppcheck warnings
  cmake/SeracCompilerFlags.cmake
  src/serac/infrastructure/about.cpp
  src/serac/infrastructure/accelerator.hpp
  src/serac/physics/base_physics.cpp
  src/serac/physics/base_physics.hpp
  src/serac/physics/boundary_conditions/boundary_condition_manager.hpp
  src/serac/physics/integrators/displacement_hyperelastic_integrator.hpp
  src/serac/physics/integrators/wrapper_integrator.hpp
  src/serac/physics/materials/hyperelastic_material.hpp
  src/serac/physics/materials/thermal_expansion_material.hpp
  src/serac/physics/solid_functional.hpp
  src/serac/physics/state/state_manager.hpp
  src/serac/physics/thermal_solid.hpp
Labels: CS

#724 Clarify/update docker build docs
  src/docs/sphinx/dev_guide/new_docker_image.rst
Labels: documentation, CS, CI, build, TPL

#723 Don't change the mesh when geometric nonlinearities are off
  data/input_files/tests/solid/qs_linear.lua
  src/serac/physics/solid.cpp
  src/serac/physics/solid_functional.hpp
  src/serac/physics/tests/serac_solid_adjoint.cpp
  src/serac/physics/tests/serac_solid_functional.cpp
  src/serac/physics/tests/serac_thermal_expansion.cpp
Labels: bug, discretization, ready for review

#725 Fix examples
  .gitlab/build_quartz.yml
  examples/CMakeLists.txt
  examples/using-with-cmake/host-config.cmake.in
  examples/using-with-cmake/serac_example.cpp
  scripts/llnl/common_build_functions.py
Labels: bug, CS, build, install

#703 Refactor the `FiniteElementVector` class
  data/input_files/default.lua
  data/input_files/tests/solid/dyn_amgx_solve.lua
  data/input_files/tests/solid/dyn_direct_solve.lua
  data/input_files/tests/solid/dyn_linesearch_solve.lua
  data/input_files/tests/solid/dyn_newmark_solve_bending_first.lua
  data/input_files/tests/solid/dyn_solve.lua
  data/input_files/tests/solid/qs_attribute_solve.lua
  data/input_files/tests/solid/qs_component_solve.lua
  data/input_files/tests/solid/qs_direct_solve.lua
  data/input_files/tests/solid/qs_linear.lua
  data/input_files/tests/solid/qs_solve.lua
  data/input_files/tests/thermal_conduction/dyn_exp_solve.lua
  data/input_files/tests/thermal_conduction/dyn_imp_solve.lua
  data/input_files/tests/thermal_conduction/dyn_imp_solve_restart.lua
  data/input_files/tests/thermal_conduction/dyn_imp_solve_time_varying.lua
  data/input_files/tests/thermal_conduction/static_solve_multiple_bcs.lua
  data/input_files/tests/thermal_solid/thermal_expansion.lua
  examples/simple_conduction/with_input_file.cpp
  examples/simple_conduction/without_input_file.cpp
  src/docs/sphinx/user_guide/simple_conduction_tutorial.rst
  src/drivers/serac.cpp
  src/serac/infrastructure/tests/CMakeLists.txt
  src/serac/infrastructure/tests/serac_error_handling.cpp
  src/serac/numerics/expr_template_impl.hpp
  src/serac/numerics/functional/tests/functional_material_state_test.cpp
  src/serac/numerics/tests/serac_odes.cpp
  src/serac/physics/base_physics.cpp
  src/serac/physics/base_physics.hpp
  src/serac/physics/boundary_conditions/CMakeLists.txt
  src/serac/physics/boundary_conditions/boundary_condition.cpp
  src/serac/physics/coefficients/sensitivity_coefficients.cpp
  src/serac/physics/materials/thermal_expansion_material.cpp
  src/serac/physics/materials/thermal_expansion_material.hpp
  src/serac/physics/solid.cpp
  src/serac/physics/solid_functional.hpp
  src/serac/physics/state/CMakeLists.txt
  src/serac/physics/state/finite_element_dual.hpp
  src/serac/physics/state/finite_element_state.cpp
  src/serac/physics/state/finite_element_state.hpp
  src/serac/physics/state/finite_element_vector.cpp
  src/serac/physics/state/finite_element_vector.hpp
  src/serac/physics/state/state_manager.cpp
  src/serac/physics/tests/CMakeLists.txt
  src/serac/physics/tests/serac_newmark_test.cpp
  src/serac/physics/tests/serac_solid.cpp
  src/serac/physics/tests/serac_solid_adjoint.cpp
  src/serac/physics/tests/serac_solid_functional_finite_diff.cpp
  src/serac/physics/tests/serac_solid_reuse_mesh.cpp
  src/serac/physics/tests/serac_solid_sensitivity.cpp
  src/serac/physics/tests/serac_thermal_functional.cpp
  src/serac/physics/tests/serac_thermal_functional_finite_diff.cpp
  src/serac/physics/tests/serac_thermal_solid_functional.cpp
  src/serac/physics/tests/serac_thermal_structural_solver.cpp
  src/serac/physics/tests/test_utilities.cpp
  src/serac/physics/thermal_conduction.cpp
  src/serac/physics/thermal_conduction_functional.hpp
  src/serac/physics/thermal_solid.cpp
  src/serac/physics/thermal_solid.hpp
Labels: discretization, ready for review, refactoring
