Repository LLNL/serac, pull requests merged in 2022-11, with the labels that each got.

#834 Remove unused parameterize functions
  src/serac/physics/heat_transfer.hpp
  src/serac/physics/materials/CMakeLists.txt
  src/serac/physics/materials/material_utils.hpp
Labels: refactoring

#836 Add a little more documentation to StateManager::reset()
  src/serac/physics/state/state_manager.hpp
Labels: bug, documentation, ready for review

#844 Add the parameters to the output state arrays
  src/serac/physics/heat_transfer.hpp
  src/serac/physics/solid_mechanics.hpp
Labels: bug, output

#706 performance refactor: batched kernel implementations
  cmake/thirdparty/SetupSeracThirdParty.cmake
  scripts/spack/configs/linux_ubuntu_22/compilers.yaml
  scripts/spack/configs/linux_ubuntu_22/packages.yaml
  scripts/spack/packages/conduit/package.py
  src/serac/infrastructure/profiling.cpp
  src/serac/numerics/functional/boundary_integral.hpp
  src/serac/numerics/functional/boundary_integral_kernels.hpp
  src/serac/numerics/functional/detail/hexahedron_H1.inl
  src/serac/numerics/functional/detail/hexahedron_Hcurl.inl
  src/serac/numerics/functional/detail/hexahedron_L2.inl
  src/serac/numerics/functional/detail/metaprogramming.hpp
  src/serac/numerics/functional/detail/qoi.inl
  src/serac/numerics/functional/detail/quadrilateral_H1.inl
  src/serac/numerics/functional/detail/quadrilateral_Hcurl.inl
  src/serac/numerics/functional/detail/quadrilateral_L2.inl
  src/serac/numerics/functional/detail/segment_H1.inl
  src/serac/numerics/functional/dof_numbering.hpp
  src/serac/numerics/functional/domain_integral.hpp
  src/serac/numerics/functional/domain_integral_kernels.hpp
  src/serac/numerics/functional/finite_element.hpp
  src/serac/numerics/functional/functional.hpp
  src/serac/numerics/functional/integral_utilities.hpp
  src/serac/numerics/functional/polynomials.hpp
  src/serac/numerics/functional/quadrature.hpp
  src/serac/numerics/functional/tensor.hpp
  src/serac/numerics/functional/tests/CMakeLists.txt
  src/serac/numerics/functional/tests/check_gradient.hpp
  src/serac/numerics/functional/tests/functional_basic_h1_scalar.cpp
  src/serac/numerics/functional/tests/functional_basic_h1_vector.cpp
  src/serac/numerics/functional/tests/functional_basic_hcurl.cpp
  src/serac/numerics/functional/tests/functional_boundary_test.cpp
  src/serac/numerics/functional/tests/functional_comparisons.cpp
  src/serac/numerics/functional/tests/functional_material_state_test.cpp
  src/serac/numerics/functional/tests/functional_multiphysics.cpp
  src/serac/numerics/functional/tests/functional_nonlinear.cpp
  src/serac/numerics/functional/tests/mfem_issue_reproducer.cu
  src/serac/numerics/functional/tests/performance/J2_material_with_AD.cpp
  src/serac/numerics/functional/tests/performance/diffusion_performance_test.cpp
  src/serac/numerics/functional/tests/performance/kernel_microbenchmark.cpp
  src/serac/numerics/functional/tests/quadrature_data_cuda.cu
  src/serac/numerics/functional/tests/tensor_unit_tests.cpp
  src/serac/numerics/functional/tests/test_tensor_ad.cpp
  src/serac/numerics/functional/tests/variadic_test_cuda.cu
  src/serac/numerics/functional/tuple.hpp
  src/serac/numerics/functional/tuple_arithmetic.hpp
  src/serac/physics/solid_mechanics.hpp
  src/serac/physics/tests/solid.cpp
  src/serac/physics/tests/solid_shape.cpp
  src/serac/physics/tests/solid_statics_patch.cpp
Labels: enhancement, ready for review, refactoring

#853 Fix the Kirchhoff typos
  src/serac/physics/materials/hyperelastic_legacy_material.hpp
  src/serac/physics/materials/solid_legacy_utils.hpp
  src/serac/physics/materials/solid_material.hpp
  src/serac/physics/solid_mechanics.hpp
  src/serac/physics/thermomechanics.hpp
Labels: documentation, quick

#851 clarify q-function requirements for solid mechanics module
  scripts/spack/configs/linux_ubuntu_22/compilers.yaml
  scripts/spack/configs/linux_ubuntu_22/packages.yaml
  src/docs/doxygen/mainpage.md
  src/docs/sphinx/dev_guide/tensor_dual.rst
  src/serac/numerics/functional/functional.hpp
  src/serac/numerics/functional/tests/tuple_arithmetic_unit_tests.cpp
  src/serac/numerics/functional/tuple_arithmetic.hpp
  src/serac/physics/solid_mechanics.hpp
Labels: documentation, ready for review, user-request, quick

#858 Make the finite element space const
  src/serac/numerics/functional/functional_qoi.inl
Labels: ready for review, quick
