Repository LLNL/serac, pull requests merged in 2022-10, with the labels that each got.

#811 fix bug in QoI constructor
  src/serac/numerics/functional/functional_qoi.inl
  src/serac/numerics/functional/tests/functional_qoi.cpp
Labels: bug, ready for review

#798 Improve gitlab integration tests logging on failure
  .gitlab-ci.yml
  scripts/gitlab/build_and_test.sh
Labels: ready for review, CI, testing

#812 Restore accidentally disabled traction patch tests
  src/serac/physics/materials/solid_functional_material.hpp
  src/serac/physics/tests/test_solid_functional_statics.cpp
Labels: ready for review

#822 initialize update_qdata
  src/serac/numerics/functional/functional.hpp
Labels: bug, user-request

#824 Add check that processors contain boundary elements
  src/serac/numerics/functional/dof_numbering.hpp
Labels: discretization, ready for review

#826 More boundary functional bugs
  src/serac/numerics/functional/functional.hpp
  src/serac/numerics/functional/functional_qoi.inl
Labels: discretization, ready for review

#828 Cleanup legacy output logic
  examples/simple_conduction/conduction.lua
  examples/simple_conduction/with_input_file.cpp
  scripts/spack/packages/glvis/package.py
  scripts/spack/packages/serac/package.py
  src/docs/sphinx/quickstart.rst
  src/docs/sphinx/user_guide/index.rst
  src/docs/sphinx/user_guide/input_schema.rst
  src/drivers/serac.cpp
  src/serac/infrastructure/input.cpp
  src/serac/infrastructure/input.hpp
  src/serac/numerics/solver_config.hpp
  src/serac/physics/tests/legacy_thermal_expansion.cpp
  src/serac/physics/tests/test_utilities.cpp
  src/serac/physics/tests/thermal_mechanics.cpp
Labels: documentation, CS, ready for review, build, TPL, input, output, testing

#815 Update the `StateManager` before saving
  src/serac/numerics/functional/dof_numbering.hpp
  src/serac/numerics/functional/functional.hpp
  src/serac/physics/base_physics.cpp
  src/serac/physics/base_physics.hpp
  src/serac/physics/heat_transfer.hpp
  src/serac/physics/solid_legacy.cpp
  src/serac/physics/solid_mechanics.hpp
  src/serac/physics/state/state_manager.cpp
  src/serac/physics/state/state_manager.hpp
  src/serac/physics/thermal_conduction_legacy.cpp
  src/serac/physics/thermal_solid_legacy.cpp
  src/serac/physics/thermomechanics.hpp
Labels: ready for review

#820 Simplify Dependencies
  examples/simple_conduction/CMakeLists.txt
  scripts/graphviz/generate_images.py
  src/drivers/CMakeLists.txt
  src/serac/infrastructure/tests/CMakeLists.txt
  src/serac/mesh/tests/CMakeLists.txt
  src/serac/numerics/functional/CMakeLists.txt
  src/serac/numerics/tests/CMakeLists.txt
  src/serac/physics/CMakeLists.txt
  src/serac/physics/boundary_conditions/CMakeLists.txt
  src/serac/physics/boundary_conditions/tests/CMakeLists.txt
  src/serac/physics/coefficients/CMakeLists.txt
  src/serac/physics/coefficients/tests/CMakeLists.txt
  src/serac/physics/integrators/CMakeLists.txt
  src/serac/physics/materials/CMakeLists.txt
  src/serac/physics/materials/tests/CMakeLists.txt
  src/serac/physics/tests/CMakeLists.txt
Labels: build

#832 Add more functions to `dual.hpp`
  src/serac/numerics/functional/dual.hpp
  src/serac/numerics/functional/tests/test_tensor_ad.cpp
Labels: enhancement, ready for review
