Repository LLNL/serac, pull requests merged in 2022-09, with the labels that each got.

#782 Improvements for LIDO
  scripts/wolfram/qoi_examples.nb
  src/docs/sphinx/dev_guide/functional.rst
  src/serac/mesh/mesh_utils.cpp
  src/serac/numerics/functional/boundary_integral.hpp
  src/serac/numerics/functional/boundary_integral_kernels.hpp
  src/serac/numerics/functional/domain_integral.hpp
  src/serac/numerics/functional/domain_integral_kernels.hpp
  src/serac/numerics/functional/functional.hpp
  src/serac/numerics/functional/functional_qoi.inl
  src/serac/numerics/functional/integral_utilities.hpp
  src/serac/numerics/functional/polynomials.hpp
  src/serac/numerics/functional/tests/CMakeLists.txt
  src/serac/numerics/functional/tests/functional_basic.cpp
  src/serac/numerics/functional/tests/functional_boundary_test.cpp
  src/serac/numerics/functional/tests/functional_comparison_L2.cpp
  src/serac/numerics/functional/tests/functional_comparisons.cpp
  src/serac/numerics/functional/tests/functional_multiphysics.cpp
  src/serac/numerics/functional/tests/functional_nonlinear.cpp
  src/serac/numerics/functional/tests/functional_qoi.cpp
  src/serac/numerics/functional/tuple_arithmetic.hpp
  src/serac/physics/materials/solid_functional_material.hpp
  src/serac/physics/solid_functional.hpp
  src/serac/physics/tests/parameterized_thermomechanics_example.cpp
  src/serac/physics/tests/serac_solid_functional.cpp
  src/serac/physics/tests/serac_solid_functional_finite_diff.cpp
  src/serac/physics/tests/serac_thermal_functional.cpp
  src/serac/physics/tests/serac_thermal_functional_finite_diff.cpp
  src/serac/physics/thermal_conduction_functional.hpp
  src/serac/physics/thermal_mechanics_functional.hpp
Labels: enhancement, discretization, ready for review

#779 Test solid mechanics with patch tests
  data/meshes/patch2D.mesh
  data/meshes/patch3D.mesh
  src/serac/physics/materials/solid_functional_material.hpp
  src/serac/physics/solid_functional.hpp
  src/serac/physics/state/finite_element_vector.cpp
  src/serac/physics/state/finite_element_vector.hpp
  src/serac/physics/tests/CMakeLists.txt
  src/serac/physics/tests/serac_solid_functional.cpp
  src/serac/physics/tests/serac_solid_functional_boundary.cpp
  src/serac/physics/tests/test_solid_functional_statics.cpp
Labels: ready for review, testing

#770 Update build instructions for macOS
  src/docs/sphinx/quickstart.rst
Labels: ready for review

#796 update macos build instructions for m1 macs
  scripts/spack/configs/darwin_monterey/compilers.yaml
  scripts/spack/configs/darwin_monterey/packages.yaml
  src/docs/sphinx/quickstart.rst
Labels: ready for review, build

#663 Add shape sensitivities to the `SolidFunctional` module
  src/serac/numerics/functional/isotropic_tensor.hpp
  src/serac/physics/common.hpp
  src/serac/physics/materials/solid_functional_material.hpp
  src/serac/physics/materials/thermal_expansion_material.hpp
  src/serac/physics/solid_functional.hpp
  src/serac/physics/state/CMakeLists.txt
  src/serac/physics/state/finite_element_dual.hpp
  src/serac/physics/state/finite_element_state.cpp
  src/serac/physics/state/finite_element_state.hpp
  src/serac/physics/state/finite_element_vector.cpp
  src/serac/physics/state/finite_element_vector.hpp
  src/serac/physics/state/state_manager.cpp
  src/serac/physics/tests/CMakeLists.txt
  src/serac/physics/tests/serac_solid_functional.cpp
  src/serac/physics/tests/serac_solid_functional_finite_diff.cpp
  src/serac/physics/tests/serac_solid_functional_shape.cpp
  src/serac/physics/tests/serac_solid_sensitivity.cpp
Labels: discretization, ready for review

#801 Minimize Axom build size
  scripts/spack/configs/mirrors.yaml
  scripts/spack/packages/axom/package.py
  scripts/spack/packages/serac/package.py
Labels: CS, ready for review, build, TPL

#805 Make mfem version more reflect actual version
  scripts/spack/packages/mfem/package.py
Labels: ready for review, build, TPL

#764 Remove bloat from our binaries
  scripts/spack/configs/blueos_3_ppc64le_ib_p9/packages.yaml
  scripts/spack/configs/docker/ubuntu20/packages.yaml
  scripts/spack/configs/toss_3_x86_64_ib/packages.yaml
  scripts/spack/packages/serac/package.py
Labels: ready for review, build

#808 Revert HDF5 build type change
  scripts/spack/packages/serac/package.py
Labels: bug, ready for review, build, TPL, user-request
