Repository LLNL/serac, pull requests merged in 2023-07, with the labels that each got.

#952 add differentiable eigenvalue calculation for small matrices
  src/serac/numerics/functional/tests/test_tensor_ad.cpp
  src/serac/numerics/functional/tuple_tensor_dual_functions.hpp
Labels: enhancement, ready for review, user-request, quick

#959 Add newer tagged versions of RAJA that will compile on Fedora 37
  scripts/spack/packages/raja/package.py
Labels: build

#957 Remove the `SetElasticityOptions` call
  src/serac/physics/materials/parameterized_solid_material.hpp
  src/serac/physics/solid_mechanics.hpp
  src/serac/physics/tests/solid.cpp
  src/serac/physics/tests/solid_shape.cpp
Labels: bug, quick
