Repository LLNL/serac, pull requests merged in 2023-01, with the labels that each got.

#871 Patched Reactions Dual Construction in SolidMechanics
  src/serac/physics/solid_mechanics.hpp
Labels: bug, quick

#875 Simplify finite element state creation
  src/serac/physics/state/finite_element_vector.cpp
  src/serac/physics/state/finite_element_vector.hpp
  src/serac/physics/tests/parameterized_thermomechanics_example.cpp
Labels: discretization, ready for review, refactoring

#880 Bugfix: some tensors in shape function routines were incorrectly shaped
  src/serac/numerics/functional/detail/hexahedron_H1.inl
  src/serac/numerics/functional/detail/hexahedron_Hcurl.inl
  src/serac/numerics/functional/detail/hexahedron_L2.inl
  src/serac/numerics/functional/detail/quadrilateral_H1.inl
  src/serac/numerics/functional/detail/quadrilateral_Hcurl.inl
  src/serac/numerics/functional/detail/quadrilateral_L2.inl
  src/serac/numerics/functional/tests/functional_comparison_L2.cpp
Labels: bug, ready for review, quick
