Repository LLNL/serac, pull requests merged in 2023-08, with the labels that each got.

#971 Add missing header geometry
  src/serac/numerics/functional/CMakeLists.txt
Labels: bug, ready for review, quick

#972 Adding more functional and functional detail headers
  src/serac/numerics/functional/CMakeLists.txt
Labels: bug, quick

#954 Pass dX/dxi to boundary q-functions
  src/serac/numerics/functional/CMakeLists.txt
  src/serac/numerics/functional/boundary_integral_kernels.hpp
  src/serac/numerics/functional/detail/tetrahedron_H1.inl
  src/serac/numerics/functional/detail/tetrahedron_L2.inl
  src/serac/numerics/functional/domain_integral_kernels.cuh
  src/serac/numerics/functional/domain_integral_kernels.hpp
  src/serac/numerics/functional/geometry.hpp
  src/serac/numerics/functional/integral_utilities.hpp
  src/serac/numerics/functional/quadrature_data.cpp
  src/serac/numerics/functional/quadrature_data.hpp
  src/serac/numerics/functional/tests/CMakeLists.txt
  src/serac/numerics/functional/tests/functional_basic_h1_scalar.cpp
  src/serac/numerics/functional/tests/functional_basic_h1_vector.cpp
  src/serac/numerics/functional/tests/functional_boundary_test.cpp
  src/serac/numerics/functional/tests/functional_multiphysics.cpp
  src/serac/numerics/functional/tests/functional_nonlinear.cpp
  src/serac/numerics/functional/tests/functional_qoi.cpp
  src/serac/numerics/functional/tests/functional_shape_derivatives.cpp
  src/serac/physics/heat_transfer.hpp
  src/serac/physics/solid_mechanics.hpp
  src/serac/physics/tests/beam_bending.cpp
  src/serac/physics/tests/lce_Brighenti_tensile.cpp
  src/serac/physics/tests/parameterized_thermomechanics_example.cpp
  src/serac/physics/tests/solid.cpp
  src/serac/physics/tests/solid_finite_diff.cpp
  src/serac/physics/tests/solid_shape.cpp
Labels: bug, enhancement, ready for review, user-request

#966 Spack-side of moving Tribol to Serac
  host-configs/lassen-blueos_3_ppc64le_ib_p9-clang@10.0.1.cmake
  host-configs/quartz-toss_4_x86_64_ib-clang@14.0.6.cmake
  host-configs/quartz-toss_4_x86_64_ib-gcc@10.3.1.cmake
  host-configs/rzansel-blueos_3_ppc64le_ib_p9-clang@10.0.1.cmake
  host-configs/rzgenie-toss_3_x86_64_ib-clang@10.0.0.cmake
  host-configs/rzgenie-toss_3_x86_64_ib-gcc@8.3.1.cmake
  scripts/spack/packages/serac/package.py
  scripts/spack/packages/tribol/package.py
  scripts/spack/specs.json
  src/serac/numerics/functional/domain_integral_kernels.hpp
  src/serac/numerics/functional/tests/functional_shape_derivatives.cpp
Labels: TPL

#967 Add pressure boundary conditions
  src/serac/physics/solid_mechanics.hpp
  src/serac/physics/tests/beam_bending.cpp
  src/serac/physics/tests/lce_Brighenti_tensile.cpp
  src/serac/physics/tests/solid.cpp
  src/serac/physics/tests/solid_dynamics_patch.cpp
  src/serac/physics/tests/solid_finite_diff.cpp
  src/serac/physics/tests/solid_statics_patch.cpp
Labels: enhancement, discretization, ready for review

#978 Remove expression templates
  src/docs/sphinx/dev_guide/expr_templates.rst
  src/docs/sphinx/dev_guide/index.rst
  src/serac/numerics/CMakeLists.txt
  src/serac/numerics/expr_template_impl.hpp
  src/serac/numerics/expr_template_ops.hpp
  src/serac/numerics/functional/tests/functional_basic_h1_scalar.cpp
  src/serac/numerics/functional/tests/functional_basic_h1_vector.cpp
  src/serac/numerics/functional/tests/functional_boundary_test.cpp
  src/serac/numerics/functional/tests/functional_comparison_L2.cpp
  src/serac/numerics/functional/tests/functional_comparisons.cpp
  src/serac/numerics/functional/tests/functional_multiphysics.cpp
  src/serac/numerics/functional/tests/functional_nonlinear.cpp
  src/serac/numerics/functional/tests/functional_shape_derivatives.cpp
  src/serac/numerics/odes.cpp
  src/serac/numerics/tests/CMakeLists.txt
  src/serac/numerics/tests/benchmark_expr_templates.cpp
  src/serac/numerics/tests/expr_templates.cpp
  src/serac/numerics/tests/odes.cpp
  src/serac/numerics/tests/operator.cpp
  src/serac/numerics/vector_expression.hpp
  src/serac/physics/heat_transfer.hpp
  src/serac/physics/tests/parameterized_thermomechanics_example.cpp
Labels: ready for review, refactoring

#984 Handle new axom repo in codevelop mode
  CMakeLists.txt
  cmake/thirdparty/SetupSeracThirdParty.cmake
Labels: CS, build

#976 Check missing headers
  azure-pipelines.yml
  scripts/azure-pipelines/linux-check.sh
  scripts/check_for_missing_headers.py
Labels: ready for review, CI, install

#989 limit lifetime of artifacts
  .gitlab-ci.yml
Labels: CI

#992 In about.cpp, print TRIBOL_VERSION_FULL
  cmake/thirdparty/SetupSeracThirdParty.cmake
  src/serac/infrastructure/CMakeLists.txt
  src/serac/infrastructure/about.cpp
Labels: ready for review

#991 Fix srun issues
  .gitlab/build_quartz.yml
Labels: bug, ready for review, CI, quick

#993 hopefully fix an issue in pow() for dual numbers
  src/serac/numerics/functional/dual.hpp
  src/serac/numerics/functional/tests/test_tensor_ad.cpp
Labels: bug, ready for review

#983 Tribol Lassen
  cmake/SeracCompilerFlags.cmake
  host-configs/lassen-blueos_3_ppc64le_ib_p9-clang@10.0.1.cmake
  scripts/spack/packages/serac/package.py
  scripts/spack/specs.json
Labels: ready for review, build, TPL
