Repository LLNL/serac, pull requests merged in 2023-11, with the labels that each got.

#1023 Fix Tribol is always built if +cuda
  scripts/spack/packages/serac/package.py
Labels: bug

#1027 Limit serac's use of axom's components
  cmake/thirdparty/SetupSeracThirdParty.cmake
  src/serac/infrastructure/CMakeLists.txt
  src/tests/CMakeLists.txt
Labels: build, TPL

#982 Contact enforcement with Tribol
  data/meshes/beam-hex-with-contact-block.mesh
  data/meshes/twohex_for_contact.mesh
  src/docs/sphinx/theory_reference/solid.rst
  src/serac/numerics/equation_solver.cpp
  src/serac/numerics/equation_solver.hpp
  src/serac/physics/CMakeLists.txt
  src/serac/physics/contact/CMakeLists.txt
  src/serac/physics/contact/contact_config.hpp
  src/serac/physics/contact/contact_data.cpp
  src/serac/physics/contact/contact_data.hpp
  src/serac/physics/contact/contact_interaction.cpp
  src/serac/physics/contact/contact_interaction.hpp
  src/serac/physics/solid_mechanics.hpp
  src/serac/physics/solid_mechanics_contact.hpp
  src/serac/physics/tests/CMakeLists.txt
  src/serac/physics/tests/contact_beam.cpp
  src/serac/physics/tests/contact_patch.cpp
Labels: enhancement, discretization, ready for review

#1029 Remove hdf5_hl hack
  cmake/thirdparty/SetupSeracThirdParty.cmake
Labels: bug, quick

#1028 Feature/tupek/thermal transient adj
  src/serac/physics/heat_transfer.hpp
  src/serac/physics/materials/parameterized_thermal_material.hpp
  src/serac/physics/materials/thermal_material.hpp
  src/serac/physics/solid_mechanics.hpp
  src/serac/physics/solid_mechanics_contact.hpp
  src/serac/physics/tests/dynamic_solid_adjoint.cpp
  src/serac/physics/tests/dynamic_thermal_adjoint.cpp
Labels: ready for review

#1002 support operations on specific parts of a mesh
  src/serac/numerics/functional/CMakeLists.txt
  src/serac/numerics/functional/boundary_integral_kernels.hpp
  src/serac/numerics/functional/detail/hexahedron_Hcurl.inl
  src/serac/numerics/functional/dof_numbering.hpp
  src/serac/numerics/functional/domain.cpp
  src/serac/numerics/functional/domain.hpp
  src/serac/numerics/functional/domain_integral_kernels.hpp
  src/serac/numerics/functional/functional.hpp
  src/serac/numerics/functional/functional_qoi.inl
  src/serac/numerics/functional/geometric_factors.cpp
  src/serac/numerics/functional/geometric_factors.hpp
  src/serac/numerics/functional/integral.hpp
  src/serac/numerics/functional/tensor.hpp
  src/serac/numerics/functional/tests/CMakeLists.txt
  src/serac/numerics/functional/tests/domain_tests.cpp
  src/serac/numerics/functional/tests/functional_qoi.cpp
  src/serac/numerics/functional/tests/functional_with_domain.cpp
  src/serac/numerics/functional/tests/geometric_factors_tests.cpp
  src/serac/physics/state/finite_element_vector.hpp
Labels: enhancement, ready for review

#1035 Default to 1 OpenMP thread for our unit tests
  cmake/SeracMacros.cmake
Labels: CS, build, testing, user-request

#1037 Update the time for quasi-static time-varying loads
  src/serac/physics/heat_transfer.hpp
  src/serac/physics/solid_mechanics.hpp
  src/serac/physics/solid_mechanics_contact.hpp
Labels: ready for review, quick
