Repository LLNL/serac, pull requests merged in 2023-05, with the labels that each got.

#894 Better nonlinear solvers with KINSOL
  azure-pipelines.yml
  data/input_files/tests/solid/qs_attribute_solve.lua
  data/input_files/tests/solid/qs_solve.lua
  data/input_files/tests/thermal_conduction/static_amgx_solve.lua
  examples/simple_conduction/without_input_file.cpp
  host-configs/docker/clang@10.0.0.cmake
  host-configs/docker/gcc@11.1.0.cmake
  host-configs/docker/gcc@9.3.0.cmake
  host-configs/lassen-blueos_3_ppc64le_ib_p9-clang@10.0.1.cmake
  host-configs/ruby-toss_3_x86_64_ib-clang@10.0.0.cmake
  host-configs/ruby-toss_3_x86_64_ib-gcc@8.3.1.cmake
  host-configs/rzansel-blueos_3_ppc64le_ib_p9-clang@10.0.1.cmake
  host-configs/rzgenie-toss_3_x86_64_ib-clang@10.0.0.cmake
  host-configs/rzgenie-toss_3_x86_64_ib-gcc@8.3.1.cmake
  scripts/azure-pipelines/docs_ignore_regexs.txt
  scripts/spack/packages/serac/package.py
  scripts/spack/packages/sundials/package.py
  src/docs/doxygen/mainpage.md
  src/docs/sphinx/dev_guide/equation_solver.rst
  src/docs/sphinx/dev_guide/index.rst
  src/docs/sphinx/theory_reference/solid.rst
  src/serac/infrastructure/initialize.cpp
  src/serac/infrastructure/profiling.hpp
  src/serac/infrastructure/tests/error_handling.cpp
  src/serac/numerics/equation_solver.cpp
  src/serac/numerics/equation_solver.hpp
  src/serac/numerics/odes.cpp
  src/serac/numerics/solver_config.hpp
  src/serac/numerics/tests/CMakeLists.txt
  src/serac/numerics/tests/equationsolver.cpp
  src/serac/numerics/tests/odes.cpp
  src/serac/physics/common.hpp
  src/serac/physics/heat_transfer.hpp
  src/serac/physics/heat_transfer_input.cpp
  src/serac/physics/heat_transfer_input.hpp
  src/serac/physics/solid_mechanics.hpp
  src/serac/physics/solid_mechanics_input.cpp
  src/serac/physics/solid_mechanics_input.hpp
  src/serac/physics/state/state_manager.cpp
  src/serac/physics/tests/parameterized_thermal.cpp
  src/serac/physics/tests/parameterized_thermomechanics_example.cpp
  src/serac/physics/tests/solid.cpp
  src/serac/physics/tests/solid_dynamics_patch.cpp
  src/serac/physics/tests/solid_finite_diff.cpp
  src/serac/physics/tests/solid_periodic.cpp
  src/serac/physics/tests/solid_shape.cpp
  src/serac/physics/tests/solid_statics_patch.cpp
  src/serac/physics/tests/thermal_dynamics_patch.cpp
  src/serac/physics/tests/thermal_finite_diff.cpp
  src/serac/physics/tests/thermal_mechanics.cpp
  src/serac/physics/tests/thermal_shape.cpp
  src/serac/physics/tests/thermal_statics_patch.cpp
  src/serac/physics/thermomechanics.hpp
Labels: enhancement, discretization, ready for review

#887 LCE tests and `SolidMechanics` initial guess helper
  src/serac/numerics/functional/functional.hpp
  src/serac/physics/base_physics.cpp
  src/serac/physics/base_physics.hpp
  src/serac/physics/materials/liquid_crystal_elastomer.hpp
  src/serac/physics/solid_mechanics.hpp
  src/serac/physics/tests/CMakeLists.txt
  src/serac/physics/tests/lce_Bertoldi_lattice.cpp
  src/serac/physics/tests/lce_Brighenti_tensile.cpp
  src/serac/physics/tests/liquid_crystal_elastomer_test.cpp
Labels: discretization, ready for review

#931 Add config section to docker spack yaml
  scripts/spack/configs/docker/ubuntu20/spack.yaml
Labels: ready for review, build, quick

#935 Disable Sundials tests when not built with Sundials
  src/serac/numerics/tests/equationsolver.cpp
  src/serac/physics/tests/lce_Bertoldi_lattice.cpp
  src/serac/physics/tests/lce_Brighenti_tensile.cpp
  src/serac/physics/tests/solid.cpp
  src/serac/physics/tests/solid_statics_patch.cpp
Labels: ready for review, build, quick

#941 fix failing thermomechanics test
  src/serac/physics/materials/solid_material.hpp
  src/serac/physics/solid_mechanics.hpp
  src/serac/physics/tests/CMakeLists.txt
  src/serac/physics/tests/beam_bending.cpp
  src/serac/physics/tests/parameterized_thermomechanics_example.cpp
Labels: ready for review, quick

#933 Allow block systems to be solved with `SuperLU`
  src/serac/numerics/equation_solver.cpp
Labels: enhancement, ready for review, quick
