Repository LLNL/serac, pull requests merged in 2023-10, with the labels that each got.

#998 Feature/tupek/transient adj
  src/serac/numerics/odes.cpp
  src/serac/numerics/odes.hpp
  src/serac/physics/base_physics.hpp
  src/serac/physics/heat_transfer.hpp
  src/serac/physics/materials/thermal_material.hpp
  src/serac/physics/solid_mechanics.hpp
  src/serac/physics/state/finite_element_vector.cpp
  src/serac/physics/state/finite_element_vector.hpp
  src/serac/physics/state/state_manager.cpp
  src/serac/physics/state/state_manager.hpp
  src/serac/physics/tests/CMakeLists.txt
  src/serac/physics/tests/dynamic_thermal_adjoint.cpp
  src/serac/physics/tests/parameterized_thermal.cpp
  src/serac/physics/tests/parameterized_thermomechanics_example.cpp
  src/serac/physics/tests/solid.cpp
  src/serac/physics/tests/solid_finite_diff.cpp
  src/serac/physics/tests/thermal_finite_diff.cpp
Labels: ready for review

#977 Clarify the inputs/outputs of a forward simulation
  cmake/thirdparty/SetupSeracThirdParty.cmake
  examples/simple_conduction/without_input_file.cpp
  scripts/azure-pipelines/docs_ignore_regexs.txt
  scripts/spack/configs/linux_ubuntu_22/spack.yaml
  src/drivers/serac.cpp
  src/serac/numerics/functional/differentiate_wrt.hpp
  src/serac/numerics/functional/dof_numbering.hpp
  src/serac/numerics/functional/functional.hpp
  src/serac/numerics/functional/tests/check_gradient.hpp
  src/serac/numerics/tests/odes.cpp
  src/serac/physics/base_physics.cpp
  src/serac/physics/base_physics.hpp
  src/serac/physics/benchmarks/benchmark_thermal.cpp
  src/serac/physics/boundary_conditions/tests/boundary_cond.cpp
  src/serac/physics/heat_transfer.hpp
  src/serac/physics/solid_mechanics.hpp
  src/serac/physics/state/CMakeLists.txt
  src/serac/physics/state/finite_element_vector.cpp
  src/serac/physics/state/finite_element_vector.hpp
  src/serac/physics/state/state_manager.cpp
  src/serac/physics/state/state_manager.hpp
  src/serac/physics/tests/beam_bending.cpp
  src/serac/physics/tests/dynamic_thermal_adjoint.cpp
  src/serac/physics/tests/lce_Bertoldi_lattice.cpp
  src/serac/physics/tests/lce_Brighenti_tensile.cpp
  src/serac/physics/tests/parameterized_thermal.cpp
  src/serac/physics/tests/parameterized_thermomechanics_example.cpp
  src/serac/physics/tests/solid.cpp
  src/serac/physics/tests/solid_dynamics_patch.cpp
  src/serac/physics/tests/solid_finite_diff.cpp
  src/serac/physics/tests/solid_periodic.cpp
  src/serac/physics/tests/solid_shape.cpp
  src/serac/physics/tests/solid_statics_patch.cpp
  src/serac/physics/tests/thermal_dynamics_patch.cpp
  src/serac/physics/tests/thermal_finite_diff.cpp
  src/serac/physics/tests/thermal_mechanics.cpp
  src/serac/physics/tests/thermal_shape.cpp
  src/serac/physics/tests/thermal_statics_patch.cpp
  src/serac/physics/thermomechanics.hpp
Labels: WIP, discretization

#1016 Forward openmp variant to strumpack
  scripts/spack/packages/serac/package.py
Labels: TPL, quick

#1015 Clarify the `setParameter` docs
  src/serac/physics/base_physics.hpp
Labels: documentation, ready for review, quick
