Repository LLNL/serac, pull requests merged in 2023-12, with the labels that each got.

#1039 add time to functional
  src/serac/numerics/functional/boundary_integral_kernels.hpp
  src/serac/numerics/functional/domain_integral_kernels.hpp
  src/serac/numerics/functional/functional.hpp
  src/serac/numerics/functional/functional_qoi.inl
  src/serac/numerics/functional/integral.hpp
  src/serac/numerics/functional/tests/check_gradient.hpp
  src/serac/numerics/functional/tests/functional_basic_h1_scalar.cpp
  src/serac/numerics/functional/tests/functional_basic_h1_vector.cpp
  src/serac/numerics/functional/tests/functional_basic_hcurl.cpp
  src/serac/numerics/functional/tests/functional_boundary_test.cpp
  src/serac/numerics/functional/tests/functional_comparison_L2.cpp
  src/serac/numerics/functional/tests/functional_comparisons.cpp
  src/serac/numerics/functional/tests/functional_comparisons_cuda.cu
  src/serac/numerics/functional/tests/functional_multiphysics.cpp
  src/serac/numerics/functional/tests/functional_nonlinear.cpp
  src/serac/numerics/functional/tests/functional_qoi.cpp
  src/serac/numerics/functional/tests/functional_shape_derivatives.cpp
  src/serac/numerics/functional/tests/functional_with_domain.cpp
  src/serac/numerics/tests/equationsolver.cpp
  src/serac/physics/heat_transfer.hpp
  src/serac/physics/solid_mechanics.hpp
  src/serac/physics/solid_mechanics_contact.hpp
  src/serac/physics/tests/lce_Brighenti_tensile.cpp
  src/serac/physics/tests/parameterized_thermomechanics_example.cpp
Labels: ready for review

#1001 Input Deck Material Rework
  data/input_files/default.lua
  data/input_files/tests/solid/dyn_amgx_solve.lua
  data/input_files/tests/solid/dyn_direct_solve.lua
  data/input_files/tests/solid/dyn_linesearch_solve.lua
  data/input_files/tests/solid/dyn_newmark_solve.lua
  data/input_files/tests/solid/dyn_newmark_solve_bending.lua
  data/input_files/tests/solid/dyn_newmark_solve_bending_first.lua
  data/input_files/tests/solid/dyn_solve.lua
  data/input_files/tests/solid/qs_attribute_solve.lua
  data/input_files/tests/solid/qs_component_solve.lua
  data/input_files/tests/solid/qs_direct_solve.lua
  data/input_files/tests/solid/qs_linear.lua
  data/input_files/tests/solid/qs_solve.lua
  data/input_files/tests/thermal_conduction/dyn_exp_solve.lua
  data/input_files/tests/thermal_conduction/dyn_imp_solve.lua
  data/input_files/tests/thermal_conduction/dyn_imp_solve_restart.lua
  data/input_files/tests/thermal_conduction/dyn_imp_solve_time_varying.lua
  data/input_files/tests/thermal_conduction/static_amgx_solve.lua
  data/input_files/tests/thermal_conduction/static_reaction_exact.lua
  data/input_files/tests/thermal_conduction/static_solve.lua
  data/input_files/tests/thermal_conduction/static_solve_multiple_bcs.lua
  data/input_files/tests/thermal_conduction/static_solve_repeated_bcs.lua
  src/docs/sphinx/user_guide/input_schema.rst
  src/serac/physics/CMakeLists.txt
  src/serac/physics/heat_transfer.hpp
  src/serac/physics/heat_transfer_input.cpp
  src/serac/physics/heat_transfer_input.hpp
  src/serac/physics/materials/CMakeLists.txt
  src/serac/physics/materials/hardening_input.cpp
  src/serac/physics/materials/hardening_input.hpp
  src/serac/physics/materials/solid_material_input.cpp
  src/serac/physics/materials/solid_material_input.hpp
  src/serac/physics/materials/thermal_material_input.cpp
  src/serac/physics/materials/thermal_material_input.hpp
  src/serac/physics/solid_mechanics.hpp
  src/serac/physics/solid_mechanics_input.cpp
  src/serac/physics/solid_mechanics_input.hpp
Labels: enhancement, ready for review, input

#1053 Fix CMake pathing for smith when codeveloping with tribol
  cmake/thirdparty/SetupSeracThirdParty.cmake
Labels: bug

#1054 Contact API updates (If no Tribol)
  .gitlab/build_quartz.yml
  src/serac/physics/contact/contact_data.cpp
  src/serac/physics/contact/contact_data.hpp
Labels: bug, ready for review, quick

#1060 Fix bug and correct parameter getter routine
  src/serac/physics/base_physics.cpp
  src/serac/physics/base_physics.hpp
  src/serac/physics/heat_transfer.hpp
  src/serac/physics/solid_mechanics.hpp
  src/serac/physics/thermomechanics.hpp
Labels: bug, ready for review, quick
