Repository LLNL/serac, pull requests merged in 2024-08, with the labels that each got.

#1187 WIP: Add small comments in Mac TPL build documentation
  src/docs/sphinx/quickstart.rst
Labels: documentation, WIP

#1194 Change default linear solver based on ordering.
  src/serac/physics/solid_mechanics.hpp
Labels: ready for review

#1196 Fix bug in near-null space setup and remove PCSetCoordinates
  src/serac/numerics/petsc_solvers.cpp
Labels: bug, ready for review

#1186 Update mfem petsc/ slepc smoketests to use GPU on CUDA builds
  src/tests/mfem_petsc_smoketest.cpp
  src/tests/mfem_slepc_smoketest.cpp
  src/tests/rc_mfem_petsc_smoketest
  src/tests/rc_mfem_petsc_smoketest_gpu
  src/tests/rc_mfem_slepc_smoketest
  src/tests/rc_mfem_slepc_smoketest_gpu
Labels: bug, gpu

#1195 lazily evaluate sparse matrix LUTs
  src/serac/numerics/functional/dof_numbering.hpp
  src/serac/numerics/functional/functional.hpp
Labels: enhancement, ready for review, quick

#1198 Add cylinder example and contact force monitoring
  data/meshes/hollow-cylinder.mesh
  examples/CMakeLists.txt
  examples/buckling/CMakeLists.txt
  examples/buckling/cylinder.cpp
  examples/buckling/cylinder_petsc_options.yml
  src/serac/numerics/equation_solver.cpp
  src/serac/numerics/equation_solver.hpp
  src/serac/numerics/solver_config.hpp
  src/serac/physics/contact/contact_data.cpp
  src/serac/physics/contact/contact_data.hpp
  src/serac/physics/solid_mechanics_contact.hpp
Labels: output

#1182 Fix issue in warm start.
  src/serac/physics/solid_mechanics.hpp
  src/serac/physics/solid_mechanics_contact.hpp
Labels: ready for review

#1199 Tupek/slepc profiling init terminate
  src/serac/infrastructure/initialize.cpp
  src/serac/infrastructure/terminator.cpp
  src/serac/numerics/tests/CMakeLists.txt
  src/serac/numerics/tests/eigensolver.cpp
Labels: ready for review, quick

#1200 Add `SERAC_ENABLE_TESTS` CMake option
  cmake/SeracBasics.cmake
  src/CMakeLists.txt
  src/docs/sphinx/quickstart.rst
  src/drivers/CMakeLists.txt
  src/serac/infrastructure/CMakeLists.txt
  src/serac/infrastructure/tests/CMakeLists.txt
  src/serac/mesh/CMakeLists.txt
  src/serac/mesh/tests/CMakeLists.txt
  src/serac/numerics/CMakeLists.txt
  src/serac/numerics/functional/CMakeLists.txt
  src/serac/numerics/functional/tests/CMakeLists.txt
  src/serac/numerics/tests/CMakeLists.txt
  src/serac/physics/CMakeLists.txt
  src/serac/physics/benchmarks/CMakeLists.txt
  src/serac/physics/boundary_conditions/CMakeLists.txt
  src/serac/physics/boundary_conditions/tests/CMakeLists.txt
  src/serac/physics/contact/CMakeLists.txt
  src/serac/physics/materials/CMakeLists.txt
  src/serac/physics/materials/tests/CMakeLists.txt
  src/serac/physics/tests/CMakeLists.txt
  src/tests/CMakeLists.txt
Labels: build, testing, user-request

#1203 Remove excess perfomance warnings in PETSc solver wrappers
  src/serac/numerics/petsc_solvers.cpp
Labels: ready for review

#1210 Guard missed test and document how to style
  examples/simple_conduction/CMakeLists.txt
  src/docs/sphinx/dev_guide/style_guide.rst
Labels: CI, build

#1179 stress extrapolation
  data/meshes/notched_plate.mesh
  src/serac/infrastructure/variant.hpp
  src/serac/numerics/functional/tensor.hpp
  src/serac/physics/CMakeLists.txt
  src/serac/physics/fit.hpp
  src/serac/physics/solid_mechanics.hpp
  src/serac/physics/tests/CMakeLists.txt
  src/serac/physics/tests/fit_test.cpp
Labels: enhancement, ready for review, output, quick

#1212 Move creation of Quadrature Data to `StateManager`
  src/serac/physics/solid_mechanics.hpp
  src/serac/physics/state/state_manager.cpp
  src/serac/physics/state/state_manager.hpp
  src/serac/physics/tests/solid.cpp
Labels: CS, refactoring

#1224 Switch CI to ruby
  .gitlab/build_toss4.yml
Labels: CI

#1217 Guard buckling example against no-petsc build
  examples/buckling/CMakeLists.txt
Labels: bug, ready for review, CI, build

#1197 Tupek/additional profiling
  src/serac/numerics/equation_solver.cpp
  src/serac/numerics/functional/dof_numbering.hpp
  src/serac/numerics/functional/functional.hpp
  src/serac/physics/solid_mechanics.hpp
  src/serac/physics/tests/solid_nonlinear_solve.cpp
Labels: ready for review

#1218 Resolve duplication issue when configuring with Ninja and codevelop
  cmake/thirdparty/SetupSeracThirdParty.cmake
Labels: bug, build
