Repository LLNL/serac, pull requests merged in 2024-02, with the labels that each got.

#1078 disambiguate by_attr implementation
  src/serac/numerics/functional/domain.hpp
  src/serac/numerics/functional/tests/domain_tests.cpp
Labels: bug, ready for review, user-request

#1021 Additional contact examples
  data/meshes/ball-nurbs.mesh
  data/meshes/beam-hex-with-contact-block.mesh
  data/meshes/ironing.mesh
  examples/CMakeLists.txt
  examples/contact/CMakeLists.txt
  examples/contact/beam_bending.cpp
  examples/contact/ironing.cpp
  examples/contact/sphere.cpp
  examples/contact/twist.cpp
  src/serac/physics/contact/contact_data.cpp
  src/serac/physics/solid_mechanics_contact.hpp
Labels: ready for review

#1084 Add extra lib64 path to find strumpack package
  cmake/thirdparty/SetupSeracThirdParty.cmake
Labels: bug, build, quick
