Repository LLNL/serac, pull requests merged in 2024-01, with the labels that each got.

#1058 Replace thermal conduction phrase with heat transfer
  data/input_files/default.lua
  data/input_files/tests/heat_transfer/dyn_exp_solve.lua
  data/input_files/tests/heat_transfer/dyn_imp_solve.lua
  data/input_files/tests/heat_transfer/dyn_imp_solve_restart.lua
  data/input_files/tests/heat_transfer/dyn_imp_solve_time_varying.lua
  data/input_files/tests/heat_transfer/static_amgx_solve.lua
  data/input_files/tests/heat_transfer/static_reaction_exact.lua
  data/input_files/tests/heat_transfer/static_solve.lua
  data/input_files/tests/heat_transfer/static_solve_multiple_bcs.lua
  data/input_files/tests/heat_transfer/static_solve_repeated_bcs.lua
  data/input_files/tests/thermal_conduction/dyn_imp_solve.lua
  data/input_files/tests/thermal_solid/thermal_expansion.lua
  examples/simple_conduction/without_input_file.cpp
  src/docs/sphinx/dev_guide/state_manager.rst
  src/docs/sphinx/user_guide/index.rst
  src/docs/sphinx/user_guide/input_schema.rst
  src/docs/sphinx/user_guide/simple_conduction_tutorial.rst
  src/drivers/CMakeLists.txt
  src/drivers/serac.cpp
  src/serac/physics/benchmarks/benchmark_thermal.cpp
  src/serac/physics/heat_transfer.hpp
  src/serac/physics/heat_transfer_input.cpp
  src/serac/physics/heat_transfer_input.hpp
  src/serac/physics/materials/parameterized_thermal_material.hpp
  src/serac/physics/materials/thermal_material.hpp
  src/serac/physics/tests/parameterized_thermal.cpp
  src/serac/physics/tests/thermal_finite_diff.cpp
  src/serac/physics/thermomechanics.hpp
  src/serac/physics/thermomechanics_input.cpp
  src/serac/physics/thermomechanics_input.hpp
Labels: documentation, ready for review

#1061 Print unexpected entries input file
  data/input_files/tests/solid/dyn_amgx_solve.lua
  data/input_files/tests/solid/dyn_direct_solve.lua
  data/input_files/tests/solid/dyn_linesearch_solve.lua
  data/input_files/tests/solid/dyn_newmark_solve.lua
  data/input_files/tests/solid/dyn_newmark_solve_bending.lua
  data/input_files/tests/solid/dyn_newmark_solve_bending_first.lua
  data/input_files/tests/solid/dyn_solve.lua
  data/input_files/tests/solid/qs_attribute_solve.lua
  data/input_files/tests/solid/qs_component_solve.lua
  data/input_files/tests/solid/qs_direct_solve.lua
  data/input_files/tests/solid/qs_linear.lua
  data/input_files/tests/solid/qs_solve.lua
  data/input_files/tests/thermal_solid/thermal_expansion.lua
  src/docs/sphinx/user_guide/command_line_options.rst
  src/drivers/serac.cpp
  src/serac/infrastructure/cli.cpp
Labels: documentation, input

#1059 Shape aware functional
  src/docs/sphinx/dev_guide/functional.rst
  src/serac/numerics/functional/CMakeLists.txt
  src/serac/numerics/functional/functional.hpp
  src/serac/numerics/functional/shape_aware_functional.hpp
  src/serac/numerics/functional/tests/functional_qoi.cpp
  src/serac/numerics/functional/tests/functional_shape_derivatives.cpp
  src/serac/physics/heat_transfer.hpp
  src/serac/physics/solid_mechanics.hpp
  src/serac/physics/solid_mechanics_contact.hpp
  src/serac/physics/tests/solid_robin_condition.cpp
Labels: discretization, ready for review

#1030 Gitlab CI bank
  .gitlab-ci.yml
  .gitlab/build_lassen.yml
  .gitlab/build_quartz.yml
Labels: CI

#1071 Test no-sundials in CI
  .gitlab/build_quartz.yml
  cmake/SeracConfigHeader.cmake
  cmake/serac-config.cmake.in
  cmake/thirdparty/SetupSeracThirdParty.cmake
  src/serac/infrastructure/initialize.cpp
  src/serac/numerics/equation_solver.cpp
  src/serac/numerics/tests/equationsolver.cpp
  src/serac/physics/tests/beam_bending.cpp
  src/serac/physics/tests/contact_beam.cpp
  src/serac/physics/tests/lce_Bertoldi_lattice.cpp
  src/serac/physics/tests/lce_Brighenti_tensile.cpp
  src/serac/physics/tests/solid_statics_patch.cpp
  src/serac/serac_config.hpp.in
Labels: CI, build
