Repository LLNL/serac, pull requests merged in 2024-06, with the labels that each got.

#1122 Remove old Serac Caliper macros
  src/docs/sphinx/dev_guide/profiling.rst
  src/serac/infrastructure/profiling.cpp
  src/serac/infrastructure/profiling.hpp
  src/serac/infrastructure/tests/profiling.cpp
  src/serac/numerics/functional/tests/functional_comparisons_cuda.cu
  src/serac/physics/benchmarks/benchmark_functional.cpp
  src/serac/physics/benchmarks/benchmark_thermal.cpp
Labels: CS, ready for review, refactoring

#1128 Switch from optparse to argparse
  scripts/llnl/build_devtools.py
  scripts/llnl/build_src.py
  scripts/llnl/build_tpls.py
Labels: ready for review, build, quick

#1121 Test docs on LC and rebuild devtools
  .gitlab/build_lassen.yml
  .gitlab/build_quartz.yml
  azure-pipelines.yml
  host-configs/lassen-blueos_3_ppc64le_ib_p9-clang@10.0.1.cmake
  host-configs/quartz-toss_4_x86_64_ib-clang@14.0.6.cmake
  host-configs/quartz-toss_4_x86_64_ib-gcc@10.3.1.cmake
  host-configs/rzansel-blueos_3_ppc64le_ib_p9-clang@10.0.1.cmake
  host-configs/rzgenie-toss_4_x86_64_ib-clang@14.0.6.cmake
  host-configs/rzgenie-toss_4_x86_64_ib-gcc@10.3.1.cmake
  scripts/azure-pipelines/linux-check.sh
  scripts/docker/dockerfile.in
  scripts/docker/dockerfile_clang-14
  scripts/docker/dockerfile_gcc-13
  scripts/llnl/build_devtools.py
  scripts/llnl/common_build_functions.py
  scripts/spack/configs/blueos_3_ppc64le_ib_p9/spack.yaml
  scripts/spack/configs/toss_4_x86_64_ib/spack.yaml
  scripts/spack/devtools.json
  src/docs/doxygen/CMakeLists.txt
  src/docs/doxygen/Doxyfile.in
  src/serac/physics/heat_transfer.hpp
  src/serac/physics/solid_mechanics.hpp
Labels: documentation, ready for review, CI

#1132 Tupek/feature/reaction sensitivities
  src/serac/numerics/functional/domain.cpp
  src/serac/numerics/functional/domain.hpp
  src/serac/physics/base_physics.hpp
  src/serac/physics/boundary_conditions/boundary_condition_manager.cpp
  src/serac/physics/boundary_conditions/boundary_condition_manager.hpp
  src/serac/physics/solid_mechanics.hpp
  src/serac/physics/state/finite_element_state.cpp
  src/serac/physics/state/finite_element_state.hpp
  src/serac/physics/tests/CMakeLists.txt
  src/serac/physics/tests/dynamic_solid_adjoint.cpp
  src/serac/physics/tests/finite_element_vector_set_over_domain.cpp
  src/serac/physics/tests/solid_reaction_adjoint.cpp
Labels: ready for review

#1144 Eigendecomposition of 3x3 symmetric tensors
  src/serac/numerics/functional/tensor.hpp
  src/serac/numerics/functional/tests/tensor_unit_tests.cpp
  src/serac/numerics/functional/tuple_tensor_dual_functions.hpp
Labels: ready for review

#1142 Improve error msg about profiling variant
  cmake/thirdparty/SetupSeracThirdParty.cmake
Labels: quick

#1134 Clear profiling libraries before loading any other libraries
  CMakeLists.txt
  cmake/thirdparty/SetupSeracThirdParty.cmake
Labels: ready for review, build, TPL

#1151 Fix lido bug relating to slepc
  cmake/thirdparty/SetupSeracThirdParty.cmake
Labels: bug, build, quick

#1154 Tupek/quasi static solve protected
  src/serac/physics/solid_mechanics.hpp
  src/serac/physics/solid_mechanics_contact.hpp
Labels: ready for review, quick

#1149 Implement finite deformation log strain J2 plasticity
  src/serac/physics/materials/solid_material.hpp
  src/serac/physics/materials/tests/nonlinear_J2_material.cpp
Labels: ready for review

#1155 Tupek/newton profiling
  src/serac/numerics/equation_solver.cpp
Labels: ready for review
