Repository LLNL/serac, pull requests merged in 2024-12, with the labels that each got.

#1279 Fix Smith CI
  scripts/llnl/common_build_functions.py
  src/drivers/CMakeLists.txt
Labels: bug, CI

#1284 `chmod` shared caliper files
  scripts/llnl/run_benchmarks.py
Labels: bug

#1290 Correct small docs mistake
  src/docs/sphinx/quickstart.rst
Labels: documentation, quick

#1294 fix benchmarks: import grp and stat
  scripts/llnl/run_benchmarks.py
Labels: bug, CI, quick

#1292 Provide a way to disable Serac benchmarks
  cmake/SeracBasics.cmake
Labels: build

#1299 Separate Smith and Serac shared SPOT locations
  scripts/llnl/common_build_functions.py
  src/docs/sphinx/dev_guide/profiling.rst
Labels: testing, quick

#1304 Fix incorrect include dir (lido fix)
  src/serac/infrastructure/CMakeLists.txt
Labels: bug, build

#1274 Simplify displacement BC interface
  examples/buckling/cylinder.cpp
  examples/contact/beam_bending.cpp
  examples/contact/ironing.cpp
  examples/contact/sphere.cpp
  examples/contact/twist.cpp
  src/serac/numerics/functional/domain.cpp
  src/serac/numerics/functional/domain.hpp
  src/serac/numerics/functional/tests/domain_tests.cpp
  src/serac/numerics/tests/odes.cpp
  src/serac/physics/benchmarks/physics_benchmark_solid_nonlinear_solve.cpp
  src/serac/physics/boundary_conditions/CMakeLists.txt
  src/serac/physics/boundary_conditions/boundary_condition_manager.cpp
  src/serac/physics/boundary_conditions/boundary_condition_manager.hpp
  src/serac/physics/boundary_conditions/components.hpp
  src/serac/physics/boundary_conditions/tests/boundary_cond.cpp
  src/serac/physics/solid_mechanics.hpp
  src/serac/physics/tests/beam_bending.cpp
  src/serac/physics/tests/contact_beam.cpp
  src/serac/physics/tests/contact_patch.cpp
  src/serac/physics/tests/contact_patch_tied.cpp
  src/serac/physics/tests/dynamic_solid_adjoint.cpp
  src/serac/physics/tests/fit_test.cpp
  src/serac/physics/tests/lce_Bertoldi_lattice.cpp
  src/serac/physics/tests/lce_Brighenti_tensile.cpp
  src/serac/physics/tests/parameterized_thermomechanics_example.cpp
  src/serac/physics/tests/quasistatic_solid_adjoint.cpp
  src/serac/physics/tests/solid.cpp
  src/serac/physics/tests/solid_dynamics_patch.cpp
  src/serac/physics/tests/solid_finite_diff.cpp
  src/serac/physics/tests/solid_multi_material.cpp
  src/serac/physics/tests/solid_periodic.cpp
  src/serac/physics/tests/solid_reaction_adjoint.cpp
  src/serac/physics/tests/solid_robin_condition.cpp
  src/serac/physics/tests/solid_shape.cpp
  src/serac/physics/tests/solid_statics_patch.cpp
  src/serac/physics/tests/thermal_mechanics.cpp
  src/serac/physics/thermomechanics.hpp
Labels: ready for review

#1302 Only error when invalid maps are passed to base physics methods
  src/serac/numerics/functional/tests/functional_basic_dg.cpp
  src/serac/physics/base_physics.hpp
Labels: ready for review
