Repository LLNL/serac, pull requests merged in 2024-07, with the labels that each got.

#1160 Feature/linear hardening
  src/serac/physics/materials/solid_material.hpp
  src/serac/physics/materials/tests/nonlinear_J2_material.cpp
Labels: ready for review

#1159 Add homebrew-based build instructions for apple silicon
  scripts/spack/configs/macos_sonoma_aarch64/spack.yaml
  src/docs/sphinx/quickstart.rst
Labels: documentation, WIP

#1163 Re-add petsc/ slepc vars to Serac config
  cmake/SeracConfigHeader.cmake
  cmake/serac-config.cmake.in
Labels: bug, build, quick

#1167 Re-add Serac Cali macros
  src/docs/sphinx/dev_guide/profiling.rst
  src/serac/infrastructure/profiling.hpp
  src/serac/infrastructure/tests/profiling.cpp
  src/serac/numerics/equation_solver.cpp
  src/serac/numerics/functional/tests/functional_comparisons_cuda.cu
  src/serac/physics/benchmarks/benchmark_functional.cpp
  src/serac/physics/benchmarks/benchmark_thermal.cpp
Labels: bug

#1162 create github actions that triggers based on comment '/style' in a PR
  .github/actions/apply-style/Dockerfile
  .github/actions/apply-style/entrypoint.sh
  .github/workflows/apply-style.yml
  CMakeLists.txt
Labels: CS, ready for review, CI, build

#1170 Resolve Smith CI issue by separating cmake and other build arguments
  .gitlab/build_lassen.yml
  .gitlab/build_quartz.yml
  scripts/gitlab/build_and_test.sh
Labels: bug, CI

#1173 Switch TOSS4 CI to ruby, remove eng bank
  .gitlab/build_quartz.yml
Labels: CI

#1174 Name CI jobs by their SYS_TYPE rather than machine name
  .gitlab-ci.yml
  .gitlab/build_blueos.yml
  .gitlab/build_toss4.yml
Labels: question, CI

#1171 Update contact and output to sum over shared components of dual vectors
  src/serac/physics/base_physics.cpp
  src/serac/physics/contact/contact_interaction.cpp
Labels: bug

#1180 Re-add eng bank, switch toss4 CI machine to dane
  .gitlab/build_toss4.yml
Labels: CI, quick

#1176 Add cmake option `SERAC_USE_VDIM_ORDERING` to change ordering of all spaces in Serac
  cmake/SeracBasics.cmake
  cmake/SeracConfigHeader.cmake
  src/docs/sphinx/quickstart.rst
  src/serac/infrastructure/CMakeLists.txt
  src/serac/infrastructure/tests/error_handling.cpp
  src/serac/numerics/functional/functional.hpp
  src/serac/numerics/functional/functional_qoi.inl
  src/serac/numerics/functional/tests/functional_basic_h1_scalar.cpp
  src/serac/numerics/functional/tests/functional_boundary_test.cpp
  src/serac/numerics/functional/tests/functional_comparison_L2.cpp
  src/serac/numerics/functional/tests/functional_comparisons.cpp
  src/serac/numerics/functional/tests/functional_comparisons_cuda.cu
  src/serac/numerics/functional/tests/functional_multiphysics.cpp
  src/serac/numerics/functional/tests/functional_nonlinear.cpp
  src/serac/numerics/functional/tests/functional_qoi.cpp
  src/serac/numerics/functional/tests/functional_shape_derivatives.cpp
  src/serac/numerics/functional/tests/functional_with_domain.cpp
  src/serac/numerics/tests/equationsolver.cpp
  src/serac/physics/benchmarks/benchmark_functional.cpp
  src/serac/physics/boundary_conditions/tests/boundary_cond.cpp
  src/serac/physics/solid_mechanics.hpp
  src/serac/physics/state/finite_element_vector.cpp
  src/serac/physics/state/finite_element_vector.hpp
  src/serac/physics/state/state_manager.cpp
  src/serac/physics/tests/finite_element_vector_set_over_domain.cpp
  src/serac/physics/tests/solid.cpp
  src/serac/physics/tests/solid_nonlinear_solve.cpp
  src/serac/serac_config.hpp.in
Labels: ready for review

#1153 Add support for using PETSc preconditioners and solvers
  src/serac/infrastructure/initialize.cpp
  src/serac/infrastructure/terminator.cpp
  src/serac/numerics/CMakeLists.txt
  src/serac/numerics/equation_solver.cpp
  src/serac/numerics/equation_solver.hpp
  src/serac/numerics/petsc_solvers.cpp
  src/serac/numerics/petsc_solvers.hpp
  src/serac/numerics/solver_config.hpp
  src/serac/numerics/tests/CMakeLists.txt
  src/serac/numerics/tests/equationsolver.cpp
  src/serac/numerics/tests/equationsolver_petsc.cpp
  src/serac/physics/solid_mechanics.hpp
  src/serac/physics/tests/contact_patch.cpp
  src/serac/physics/tests/parameterized_thermomechanics_example.cpp
  src/serac/physics/tests/solid_shape.cpp
Labels: enhancement, ready for review
