Repository LLNL/serac, pull requests merged in 2024-05, with the labels that each got.

#1102 Build slepc
  azure-pipelines.yml
  cmake/SeracConfigHeader.cmake
  cmake/serac-config.cmake.in
  cmake/thirdparty/FindPETSc.cmake
  cmake/thirdparty/FindSLEPc.cmake
  cmake/thirdparty/SetupSeracThirdParty.cmake
  host-configs/docker/clang@14.0.0.cmake
  host-configs/docker/gcc@13.1.0.cmake
  host-configs/lassen-blueos_3_ppc64le_ib_p9-clang@10.0.1.cmake
  host-configs/quartz-toss_4_x86_64_ib-clang@14.0.6.cmake
  host-configs/quartz-toss_4_x86_64_ib-gcc@10.3.1.cmake
  host-configs/rzansel-blueos_3_ppc64le_ib_p9-clang@10.0.1.cmake
  host-configs/rzgenie-toss_4_x86_64_ib-clang@14.0.6.cmake
  host-configs/rzgenie-toss_4_x86_64_ib-gcc@10.3.1.cmake
  scripts/docker/dockerfile.in
  scripts/docker/dockerfile_clang-14
  scripts/docker/dockerfile_gcc-13
  scripts/spack/configs/toss_4_x86_64_ib/spack.yaml
  scripts/spack/packages/serac/package.py
  src/serac/serac_config.hpp.in
  src/tests/CMakeLists.txt
  src/tests/slepc_smoketest.cpp
Labels: build, TPL

#1116 Add ninja option to configure script
  config-build.py
Labels: build, quick

#1118 Give jobs a deadline on Quartz
  .gitlab/build_quartz.yml
  src/docs/sphinx/dev_guide/codevelop.rst
  src/docs/sphinx/dev_guide/testing.rst
  src/serac/numerics/functional/CMakeLists.txt
  src/serac/numerics/functional/tests/CMakeLists.txt
  src/serac/numerics/functional/tests/bug_boundary_qoi.cpp
Labels: CI

#1120 Remove warning about broken integration tests in driver
  src/drivers/serac.cpp
Labels: quick

#1123 Guard tests against PETSC/SLEPC not being enabled
  src/tests/CMakeLists.txt
Labels: bug, build, TPL

#1113 Add `SERAC_ENABLE_BENCHMARKS` cmake option. Test profiling/ benchmarks in CI.
  .gitlab/build_lassen.yml
  .gitlab/build_quartz.yml
  cmake/SeracBasics.cmake
  scripts/gitlab/build_and_test.sh
Labels: question, build

#1126 Gitlab: batch runner
  .gitlab-ci.yml
  .gitlab/build_lassen.yml
  .gitlab/build_quartz.yml
Labels: CS, ready for review, CI
