Repository LLNL/serac, pull requests merged in 2024-09, with the labels that each got.

#1234 Change git strategy to start from a clean slate each time
  .gitlab-ci.yml
Labels: ready for review, CI

#1239 No Optional Solvers CI Job
  .gitlab/build_toss4.yml
Labels: CI

#1240 Track serac version and compiler when benchmarking
  src/serac/infrastructure/about.cpp
  src/serac/infrastructure/about.hpp
  src/serac/infrastructure/profiling.cpp
  src/serac/serac_config.hpp.in
Labels: testing
