Repository LLNL/serac, pull requests merged in 2024-10, with the labels that each got.

#1251 Option to increase problem size of nonlinear solve benchmark (small or large)
  src/serac/physics/benchmarks/physics_benchmark_solid_nonlinear_solve.cpp
Labels: testing

#1238 Add adjoint load for the case of adjoints associated with resultant/dual forces.
  src/serac/physics/base_physics.hpp
  src/serac/physics/solid_mechanics.hpp
  src/serac/physics/tests/dynamic_solid_adjoint.cpp
  src/serac/physics/tests/quasistatic_solid_adjoint.cpp
  src/serac/physics/tests/solid_reaction_adjoint.cpp
Labels: ready for review

#1255 Tupek/checkpoint to disk again
  src/serac/physics/base_physics.cpp
  src/serac/physics/solid_mechanics.hpp
  src/serac/physics/state/state_manager.cpp
  src/serac/physics/tests/dynamic_solid_adjoint.cpp
Labels: WIP
