Repository LLNL/serac, pull requests merged in 2024-03, with the labels that each got.

#1086 Dynamic history in memory
  src/serac/physics/base_physics.cpp
  src/serac/physics/base_physics.hpp
  src/serac/physics/heat_transfer.hpp
  src/serac/physics/solid_mechanics.hpp
  src/serac/physics/tests/dynamic_solid_adjoint.cpp
  src/serac/physics/tests/dynamic_thermal_adjoint.cpp
Labels: ready for review

#1090 Use clang 14 for devtools (changes style!)
  .github/workflows/docker_build_tpls.yml
  CMakeLists.txt
  azure-pipelines.yml
  host-configs/docker/clang@14.0.0.cmake
  host-configs/docker/clang@15.0.7.cmake
  host-configs/lassen-blueos_3_ppc64le_ib_p9-clang@10.0.1.cmake
  host-configs/quartz-toss_4_x86_64_ib-clang@14.0.6.cmake
  host-configs/quartz-toss_4_x86_64_ib-gcc@10.3.1.cmake
  host-configs/rzansel-blueos_3_ppc64le_ib_p9-clang@10.0.1.cmake
  host-configs/rzgenie-toss_4_x86_64_ib-clang@14.0.6.cmake
  host-configs/rzgenie-toss_4_x86_64_ib-gcc@10.3.1.cmake
  scripts/docker/dockerfile_clang-14
  scripts/spack/configs/blueos_3_ppc64le_ib_p9/spack.yaml
  scripts/spack/configs/docker/ubuntu22/spack.yaml
  scripts/spack/configs/toss_4_x86_64_ib/spack.yaml
  scripts/spack/devtools_configs/blueos_3_ppc64le_ib_p9/spack.yaml
  scripts/spack/devtools_configs/toss_3_x86_64_ib/spack.yaml
  scripts/spack/devtools_configs/toss_4_x86_64_ib/spack.yaml
  scripts/spack/packages/serac/package.py
  scripts/spack/packages/serac_devtools/package.py
  scripts/spack/specs.json
  src/serac/infrastructure/tests/error_handling.cpp
  src/serac/infrastructure/tests/input.cpp
  src/serac/mesh/mesh_utils.cpp
  src/serac/mesh/tests/mesh_generation.cpp
  src/serac/numerics/functional/differentiate_wrt.hpp
  src/serac/numerics/functional/functional.hpp
  src/serac/numerics/functional/quadrature_data.hpp
  src/serac/numerics/functional/tests/domain_tests.cpp
  src/serac/numerics/functional/tests/hcurl_unit_tests.cpp
  src/serac/numerics/functional/tests/test_newton.cpp
  src/serac/numerics/tests/odes.cpp
  src/serac/physics/boundary_conditions/boundary_condition_manager.hpp
  src/serac/physics/contact/contact_data.cpp
  src/serac/physics/heat_transfer.hpp
  src/serac/physics/materials/tests/thermomechanical_material.cpp
  src/serac/physics/materials/thermal_material_input.cpp
  src/serac/physics/state/state_manager.cpp
  src/serac/physics/tests/contact_beam.cpp
  src/serac/physics/tests/contact_patch.cpp
  src/serac/physics/tests/lce_Brighenti_tensile.cpp
Labels: build, TPL, testing

#1091 Move to `tee` for build scripts
  scripts/llnl/common_build_functions.py
Labels: CS, ready for review, CI, build

#1092 Basic functional profiling
  scripts/spack/configs/linux_ubuntu_22/spack.yaml
  src/docs/sphinx/quickstart.rst
  src/serac/physics/benchmarks/CMakeLists.txt
  src/serac/physics/benchmarks/benchmark_functional.cpp
  src/serac/physics/benchmarks/benchmark_thermal.cpp
Labels: ready for review, quick

#1089 Fix mfem failing to include link location for mpi_mpifh
  cmake/thirdparty/SetupSeracThirdParty.cmake
  scripts/spack/configs/darwin/spack.yaml
  scripts/spack/configs/darwin_monterey/spack.yaml
Labels: WIP, build

#1096 Adding missing caliper include dir
  cmake/thirdparty/SetupSeracThirdParty.cmake
Labels: bug, build

#1087 Build Serac with PETSc
  cmake/SeracConfigHeader.cmake
  cmake/serac-config.cmake.in
  cmake/thirdparty/FindPETSc.cmake
  cmake/thirdparty/SetupSeracThirdParty.cmake
  host-configs/lassen-blueos_3_ppc64le_ib_p9-clang@10.0.1.cmake
  host-configs/quartz-toss_4_x86_64_ib-clang@14.0.6.cmake
  host-configs/quartz-toss_4_x86_64_ib-gcc@10.3.1.cmake
  host-configs/rzansel-blueos_3_ppc64le_ib_p9-clang@10.0.1.cmake
  host-configs/rzgenie-toss_4_x86_64_ib-clang@14.0.6.cmake
  host-configs/rzgenie-toss_4_x86_64_ib-gcc@10.3.1.cmake
  scripts/spack/packages/serac/package.py
  scripts/spack/specs.json
  src/serac/serac_config.hpp.in
  src/tests/CMakeLists.txt
  src/tests/petsc_smoketest.cpp
Labels: build, TPL

#1100 Fix FindPETSc.cmake path to use cmake current list dir
  cmake/serac-config.cmake.in
Labels: bug, ready for review, build
