Repository LLNL/serac, pull requests merged in 2025-05, with the labels that each got.

#1381 LiDO bugfix: don't remove from mpi exec list if empty
  scripts/spack/packages/serac/package.py
Labels: WIP, TPL

#1370 Tupek/residual fast vjp
  src/serac/numerics/functional/dual.hpp
  src/serac/numerics/functional/shape_aware_functional.hpp
  src/serac/numerics/functional/tensor.hpp
  src/serac/physics/base_physics.hpp
  src/serac/physics/functional_residual.hpp
  src/serac/physics/heat_transfer.hpp
  src/serac/physics/residual.hpp
  src/serac/physics/solid_residual.hpp
  src/serac/physics/tests/test_functional_residual.cpp
  src/serac/physics/tests/test_solid_residual.cpp
Labels: ready for review

#1380 Docs for TPL build for Ubuntu 24
  host-configs/other/tempus52-linux-ubuntu24.04-skylake-clang@14.0.6.cmake
  scripts/spack/configs/other/tempus52/spack.yaml
  scripts/spack/packages/serac/package.py
  src/docs/sphinx/dev_guide/index.rst
  src/docs/sphinx/dev_guide/ubuntu_build.rst
Labels: documentation, ready for review, build, TPL

#1373 Unified headers
  cmake/SeracMacros.cmake
  examples/CMakeLists.txt
  examples/buckling/cylinder.cpp
  examples/conduction/CMakeLists.txt
  examples/conduction/simple_conduction.cpp
  examples/contact/beam_bending.cpp
  examples/contact/ironing.cpp
  examples/contact/sphere.cpp
  examples/contact/twist.cpp
  examples/uniaxial/uniaxial_tension.cpp
  host-configs/other/tempus52-linux-ubuntu24.04-skylake-clang@14.0.6.cmake
  src/CMakeLists.txt
  src/docs/sphinx/user_guide/simple_conduction_tutorial.rst
  src/serac/infrastructure/CMakeLists.txt
  src/serac/mesh/CMakeLists.txt
  src/serac/numerics/CMakeLists.txt
  src/serac/numerics/functional/CMakeLists.txt
  src/serac/physics/CMakeLists.txt
  src/serac/physics/boundary_conditions/CMakeLists.txt
  src/serac/physics/contact/CMakeLists.txt
  src/serac/physics/fit.hpp
  src/serac/physics/materials/CMakeLists.txt
  src/serac/physics/materials/green_saint_venant_thermoelastic.hpp
  src/serac/physics/materials/parameterized_thermoelastic_material.hpp
  src/serac/physics/state/CMakeLists.txt
Labels: CS, ready for review, user-request

#1386 bugfix: Fix host config name in mac mini script
  scripts/shared-macmini/build-and-test.sh
Labels: bug, quick

#1388 Increase "no optional solvers" CI Job Allocation time to prevent CI failures
  .gitlab/build_toss4.yml
Labels: CI, quick

#1384 Prevent maybe-uninitialized error on GCC Release builds
  src/serac/numerics/equation_solver.cpp
Labels: bug
