Repository LLNL/serac, pull requests merged in 2025-04, with the labels that each got.

#1355 Resolve some undefined behavior reported by -fsanitize=undefined
  src/serac/numerics/functional/quadrature_data.cpp
  src/serac/numerics/functional/tests/functional_basic_dg.cpp
  src/serac/numerics/functional/tests/functional_qoi.cpp
Labels: bug

#1258 Add Quadrature Data to Sidre
  src/serac/numerics/functional/quadrature_data.hpp
  src/serac/physics/solid_mechanics.hpp
  src/serac/physics/state/state_manager.cpp
  src/serac/physics/state/state_manager.hpp
  src/serac/physics/state/tests/CMakeLists.txt
  src/serac/physics/state/tests/test_state_manager.cpp
  src/serac/physics/tests/solid_robin_condition.cpp
  src/serac/physics/tests/thermal_nonlinear_solve.cpp
  src/serac/physics/tests/thermal_robin_condition.cpp
Labels: ready for review

#1363 Tupek/print helper
  src/serac/infrastructure/debug_print.hpp
  src/serac/infrastructure/tests/CMakeLists.txt
  src/serac/infrastructure/tests/debug_print.cpp
Labels: ready for review, quick

#1368 Bugfix: call `refineAndDistribute` in `physics_benchmark_solid_nonlinear_solve`
  .gitlab-ci.yml
  src/serac/physics/benchmarks/physics_benchmark_solid_nonlinear_solve.cpp
Labels: bug
