Repository LLNL/serac, pull requests merged in 2025-06, with the labels that each got.

#1391 Fix vjp dual types
  src/serac/physics/functional_residual.hpp
  src/serac/physics/residual.hpp
  src/serac/physics/tests/test_functional_residual.cpp
  src/serac/physics/tests/test_heat_residual.cpp
  src/serac/physics/tests/test_solid_residual.cpp
Labels: ready for review

#1333 Tupek/add serac adjoint math to contact
  cmake/serac-config.cmake.in
  cmake/thirdparty/SetupSeracThirdParty.cmake
  data/meshes/contact_two_blocks.g
  src/serac/physics/contact/contact_data.cpp
  src/serac/physics/contact/contact_data.hpp
  src/serac/physics/solid_mechanics.cpp
  src/serac/physics/solid_mechanics.hpp
  src/serac/physics/solid_mechanics_contact.hpp
  src/serac/physics/tests/CMakeLists.txt
  src/serac/physics/tests/contact_solid_adjoint.cpp
  src/serac/physics/tests/tribol_finite_diff.cpp
  src/serac/serac_config.hpp.in
Labels: ready for review

#1402 Restore tdof ebc method
  src/serac/physics/boundary_conditions/boundary_condition_manager.cpp
  src/serac/physics/boundary_conditions/boundary_condition_manager.hpp
  src/serac/physics/solid_mechanics.hpp
  src/serac/physics/tests/solid.cpp
Labels: ready for review

#1404 Fix ARPACK include path
  cmake/thirdparty/FindARPACK.cmake
  scripts/spack/configs/versions.yaml
Labels: ready for review

#1400 Run lengthier examples in nightly CI
  .github/workflows/ci-tests.yml
  .gitlab-ci.yml
  .gitlab/build_blueos.yml
  .gitlab/build_toss4.yml
  .gitlab/build_toss4_cray.yml
  cmake/SeracMacros.cmake
  cmake/serac-config.cmake.in
  examples/CMakeLists.txt
  examples/buckling/CMakeLists.txt
  examples/contact/CMakeLists.txt
  examples/uniaxial/CMakeLists.txt
  examples/using-with-cmake/host-config.cmake.in
  scripts/llnl/build_devtools.py
  scripts/llnl/build_tpls.py
  scripts/llnl/common_build_functions.py
  scripts/llnl/run_examples.py
Labels: CI

#1410 Modularize unified header macro for Smith
  cmake/SeracMacros.cmake
Labels: bug, build, quick

#1414 Fix zlib path on mac mini spack env file
  scripts/spack/configs/macos_sonoma_aarch64/spack.yaml
Labels: quick
