Repository LLNL/serac, pull requests merged in 2025-08, with the labels that each got.

#1415 DG parallelization
  src/serac/numerics/functional/domain.cpp
  src/serac/numerics/functional/domain.hpp
  src/serac/numerics/functional/element_restriction.cpp
  src/serac/numerics/functional/functional.hpp
  src/serac/numerics/functional/functional_qoi.inl
  src/serac/numerics/functional/geometric_factors.cpp
  src/serac/numerics/functional/tests/CMakeLists.txt
  src/serac/numerics/functional/tests/dg_ghost_face_index.cpp
  src/serac/numerics/functional/tests/dg_restriction_operators.cpp
  src/serac/numerics/functional/tests/domain_tests.cpp
  src/serac/numerics/functional/tests/element_restriction_tests.cpp
  src/serac/numerics/functional/tests/functional_basic_dg.cpp
  src/serac/numerics/functional/tests/geometric_factors_tests.cpp
  src/serac/numerics/functional/typedefs.hpp
  src/serac/physics/state/finite_element_state.cpp
Labels: ready for review

#1434 Switch TOSS4 CI to CZDane
  .gitlab/build_blueos.yml
  .gitlab/build_toss4.yml
Labels: CI

#1433 Add basic serac mesh wrapper unit test
  config-build.py
  src/serac/physics/mesh.hpp
  src/serac/physics/tests/CMakeLists.txt
  src/serac/physics/tests/test_mesh_wrapper.cpp
Labels: WIP, testing

#1439 Reduce CI allocation times
  .gitlab/build_blueos.yml
  .gitlab/build_toss4.yml
  .gitlab/build_toss4_cray.yml
Labels: CI

#1416 Run some code checks
  src/serac/numerics/equation_solver.cpp
  src/serac/numerics/functional/functional.hpp
  src/serac/numerics/petsc_solvers.cpp
  src/serac/numerics/tests/odes.cpp
  src/serac/physics/heat_transfer.hpp
  src/serac/physics/solid_mechanics.hpp
  src/serac/physics/thermomechanics_monolithic.hpp
Labels: ready for review

#1436 Tupek/residual interface adjustments
  src/serac/physics/CMakeLists.txt
  src/serac/physics/base_physics.cpp
  src/serac/physics/base_physics.hpp
  src/serac/physics/field_types.hpp
  src/serac/physics/functional_objective.hpp
  src/serac/physics/functional_residual.hpp
  src/serac/physics/functional_weak_form.hpp
  src/serac/physics/heat_transfer.hpp
  src/serac/physics/heat_transfer_weak_form.hpp
  src/serac/physics/mesh.cpp
  src/serac/physics/mesh.hpp
  src/serac/physics/residual.hpp
  src/serac/physics/scalar_objective.hpp
  src/serac/physics/solid_mechanics.hpp
  src/serac/physics/solid_mechanics_contact.hpp
  src/serac/physics/solid_weak_form.hpp
  src/serac/physics/state/state_manager.cpp
  src/serac/physics/state/state_manager.hpp
  src/serac/physics/tests/CMakeLists.txt
  src/serac/physics/tests/solid_finite_diff.cpp
  src/serac/physics/tests/test_functional_weak_form.cpp
  src/serac/physics/tests/test_heat_weak_form.cpp
  src/serac/physics/tests/test_kinematic_objective.cpp
  src/serac/physics/tests/test_solid_weak_form.cpp
  src/serac/physics/tests/thermal_mechanics.cpp
  src/serac/physics/thermomechanics_monolithic.hpp
  src/serac/physics/weak_form.hpp
Labels: ready for review

#1441 Nonlin Benchmark use enums from `solver_config.hpp`
  src/serac/numerics/solver_config.hpp
  src/serac/physics/benchmarks/physics_benchmark_solid_nonlinear_solve.cpp
Labels: refactoring

#1442 Fix using with cmake example of serac when running within smith repo
  examples/CMakeLists.txt
Labels: bug, install
