Repository LLNL/serac, pull requests merged in 2025-01, with the labels that each got.

#1287 Transition Azure Pipelines to Github Actions
  .github/workflows/ci-tests.yml
  README.md
  azure-pipelines.yml
  scripts/azure-pipelines/DummyTest.xml
  scripts/github-actions/docs_ignore_regexs.txt
  scripts/github-actions/linux-check.sh
  scripts/llnl/build_src.py
  scripts/llnl/common_build_functions.py
  src/docs/sphinx/dev_guide/new_docker_image.rst
  src/docs/sphinx/quickstart.rst
Labels: ready for review, CI

#1306 Small changes to Memory Checking docs
  src/docs/sphinx/dev_guide/memory_checking.rst
Labels: documentation

#1311 Smith fix: serac config header use PROJECT_BINARY_DIR
  cmake/SeracConfigHeader.cmake
Labels: bug

#1310 Change displacement and velocity setters to use serac tensors
  src/serac/physics/solid_mechanics.hpp
  src/serac/physics/state/CMakeLists.txt
  src/serac/physics/state/finite_element_state.hpp
  src/serac/physics/state/tests/CMakeLists.txt
  src/serac/physics/state/tests/test_finite_element_state.cpp
  src/serac/physics/tests/beam_bending.cpp
  src/serac/physics/tests/fit_test.cpp
  src/serac/physics/tests/lce_Bertoldi_lattice.cpp
  src/serac/physics/tests/lce_Brighenti_tensile.cpp
  src/serac/physics/tests/parameterized_thermomechanics_example.cpp
  src/serac/physics/tests/solid.cpp
  src/serac/physics/tests/solid_dynamics_patch.cpp
  src/serac/physics/tests/solid_finite_diff.cpp
  src/serac/physics/tests/solid_periodic.cpp
  src/serac/physics/tests/solid_robin_condition.cpp
  src/serac/physics/tests/solid_shape.cpp
  src/serac/physics/tests/thermal_mechanics.cpp
  src/serac/physics/thermomechanics.hpp
Labels: ready for review

#1242 Setting up team's Mac mini
  scripts/shared-macmini/build-and-test.sh
  scripts/spack/configs/macos_sonoma_aarch64/spack.yaml
  src/docs/sphinx/dev_guide/index.rst
  src/docs/sphinx/dev_guide/macmini.rst
  src/docs/sphinx/quickstart.rst
Labels: documentation, ready for review, CI
